# -*- coding: utf-8 -*-
from gen_exos import T, Q, P, o, make_ch

make_ch("chapitre-11", "chapitre-11.md", T("Chapitre 11 — Iframe", "Chapter 11 — Iframe", "الفصل 11 — Iframe"),
[
    Q("iframe signifie :", "iframe means:", "iframe تعني:",
      [o("inline frame (cadre dans la page)", "inline frame (frame in the page)", "إطار داخلي (إطار في الصفحة)"), o("image frame PNG", "PNG image frame", "إطار صورة PNG"), o("icon font", "icon font", "خط أيقونات"), o("input form", "input form", "نموذج إدخال")], 0, "Fenêtre dans la fenêtre.", "Window in the window.", "نافذة داخل النافذة."),
    Q("src d’iframe :", "iframe src:", "src لـ iframe:",
      [o("URL ou fichier HTML à afficher", "URL or HTML file to display", "رابط أو ملف HTML للعرض"), o("un type audio/mpeg", "an audio/mpeg type", "نوع audio/mpeg"), o("un alt obligatoire d’img", "a required img alt", "alt إلزامي لـ img"), o("un li", "an li", "li")], 0, "Destination du cadre.", "Frame destination.", "وجهة الإطار."),
    Q("YouTube : URL embed :", "YouTube: embed URL:", "يوتيوب: رابط embed:",
      [o("/embed/ID pas watch?v=", "/embed/ID not watch?v=", "/embed/ID وليس watch?v="), o("seulement un mp3", "an mp3 only", "mp3 فقط"), o("un ol", "an ol", "ol"), o("un charset", "a charset", "charset")], 0, "Partager → Intégrer.", "Share → Embed.", "مشاركة → تضمين."),
    Q("Video locale mp4 → :", "Local mp4 video →", "فيديو mp4 محلي →",
      [o("élément video, pas iframe", "video element, not iframe", "عنصر video لا iframe"), o("iframe obligatoire", "required iframe", "iframe إلزامي"), o("ul", "ul", "ul"), o("mark", "mark", "mark")], 0, "Chaque outil son usage.", "Each tool its use.", "لكل أداة استخدام."),
    Q("width et height :", "width and height:", "width و height:",
      [o("taille du cadre", "frame size", "حجم الإطار"), o("couleur du texte", "text color", "لون النص"), o("UTF-8", "UTF-8", "UTF-8"), o("favicon", "favicon", "أيقونة تبويب")], 0, "560×315 souvent YouTube.", "560×315 often YouTube.", "560×315 غالبًا ليوتيوب."),
    Q("title sur iframe :", "title on iframe:", "title على iframe:",
      [o("accessibilité (décrire le cadre)", "accessibility (describe the frame)", "إتاحة (وصف الإطار)"), o("remplace src", "replaces src", "يعوّض src"), o("est un h1", "is an h1", "h1"), o("crée un mp3", "creates an mp3", "ينشئ mp3")], 0, "Important.", "Important.", "مهم."),
    Q("allowfullscreen :", "allowfullscreen:", "allowfullscreen:",
      [o("autorise le plein écran (YouTube)", "allows fullscreen (YouTube)", "يسمح بملء الشاشة (يوتيوب)"), o("crée une liste", "creates a list", "ينشئ قائمة"), o("est un dt", "is a dt", "dt"), o("est charset", "is charset", "charset")], 0, "Attribut YouTube.", "YouTube attribute.", "سمة يوتيوب."),
    Q("Tous les sites autorisent-ils l’iframe ?", "Do all sites allow iframe?", "هل كل المواقع تسمح بـ iframe؟",
      [o("Non (sécurité)", "No (security)", "لا (أمان)"), o("Oui toujours", "Yes always", "نعم دائمًا"), o("Seulement les PNG", "PNG only", "PNG فقط"), o("Seulement ol", "ol only", "ol فقط")], 0, "X-Frame-Options etc.", "X-Frame-Options etc.", "X-Frame-Options إلخ."),
    Q("Un iframe trop nombreux :", "Too many iframes:", "كثرة iframe:",
      [o("ralentit la page", "slows the page", "تبطئ الصفحة"), o("améliore UTF-8", "improves UTF-8", "تحسّن UTF-8"), o("remplace head", "replaces head", "تعوّض head"), o("crée des li", "creates li", "تنشئ li")], 0, "Page plus lourde.", "Heavier page.", "صفحة أثقل."),
    Q("Le CSS de ta page :", "Your page CSS:", "CSS صفحتك:",
      [o("ne stylise pas l’intérieur du site externe", "does not style the inside of the external site", "لا ينسّق داخل الموقع الخارجي"), o("change YouTube en vert forcément", "always turns YouTube green", "يجعل يوتيوب أخضر حتمًا"), o("supprime src", "removes src", "يحذف src"), o("devient un audio", "becomes audio", "يصبح audio")], 0, "Page séparée.", "Separate page.", "صفحة منفصلة."),
    Q("Fichier local chapitre 10 dans iframe :", "Local chapter 10 file in iframe:", "ملف الفصل 10 المحلي في iframe:",
      [o("src=\"../chapitre-10/index.html\"", "src=\"../chapitre-10/index.html\"", "src=\"../chapitre-10/index.html\""), o("src=\"audio.mp3\" comme iframe YouTube", "src=\"audio.mp3\" as YouTube iframe", "src=\"audio.mp3\" كـ iframe يوتيوب"), o("src sans chemin", "src with no path", "src بلا مسار"), o("href sur iframe", "href on iframe", "href على iframe")], 0, "Chemin relatif.", "Relative path.", "مسار نسبي."),
    Q("loading=\"lazy\" :", "loading=\"lazy\":", "loading=\"lazy\":",
      [o("charge le cadre plus tard (performance)", "loads the frame later (performance)", "يحمّل الإطار لاحقًا (أداء)"), o("met en gras", "makes bold", "يجعل غامقًا"), o("est un ol", "is an ol", "ol"), o("est un emoji", "is an emoji", "إيموجي")], 0, "Utile.", "Useful.", "مفيد."),
    Q("frameborder est :", "frameborder is:", "frameborder هو:",
      [o("ancien ; préférer le CSS border", "old; prefer CSS border", "قديم؛ فضّل CSS border"), o("obligatoire HTML5", "required HTML5", "إلزامي HTML5"), o("un type mp4", "an mp4 type", "نوع mp4"), o("un header", "a header", "header")], 0, "HTML5 moderne.", "Modern HTML5.", "HTML5 حديث."),
    Q("Maps / carte :", "Maps:", "الخرائط:",
      [o("souvent un iframe aussi", "often an iframe too", "غالبًا iframe أيضًا"), o("uniquement ul", "ul only", "ul فقط"), o("uniquement b", "b only", "b فقط"), o("uniquement source", "source only", "source فقط")], 0, "Même idée YouTube.", "Same idea as YouTube.", "نفس فكرة يوتيوب."),
    Q("allow=\"...\" YouTube :", "allow=\"...\" YouTube:", "allow=\"...\" يوتيوب:",
      [o("permissions (autoplay, fullscreen…)", "permissions (autoplay, fullscreen…)", "أذونات (تشغيل تلقائي، ملء الشاشة…)"), o("un dt", "a dt", "dt"), o("un charset", "a charset", "charset"), o("un favicon", "a favicon", "أيقونة تبويب")], 0, "Copié depuis YouTube.", "Copied from YouTube.", "منسوخ من يوتيوب."),
    Q("iframe n’est PAS :", "iframe is NOT:", "iframe ليس:",
      [o("l’élément video pour un mp4 à toi", "the video element for your own mp4", "عنصر video لملف mp4 الخاص بك"), o("un cadre", "a frame", "إطارًا"), o("capable d’afficher une page", "able to display a page", "قادرًا على عرض صفحة"), o("utile pour YouTube", "useful for YouTube", "مفيدًا ليوتيوب")], 0, "video ≠ iframe.", "video ≠ iframe.", "video ≠ iframe."),
    Q("On peut iframe un autre chapitre du cours :", "We can iframe another course chapter:", "يمكن عمل iframe لفصل آخر من الدورة:",
      [o("oui, fichier HTML local", "yes, local HTML file", "نعم، ملف HTML محلي"), o("non, interdit", "no, forbidden", "لا، ممنوع"), o("seulement en MP3", "only in MP3", "بـ MP3 فقط"), o("seulement sans src", "only without src", "بدون src فقط")], 0, "Exemple chapitre 11.", "Chapter 11 example.", "مثال الفصل 11."),
    Q("Sandbox :", "Sandbox:", "Sandbox:",
      [o("restreint ce que l’iframe a le droit de faire", "restricts what the iframe may do", "يقيّد ما يحق لـ iframe فعله"), o("une liste ol", "an ol list", "قائمة ol"), o("un emoji", "an emoji", "إيموجي"), o("un h1", "an h1", "h1")], 0, "Sécurité avancée.", "Advanced security.", "أمان متقدم."),
    Q("Le contenu iframe est :", "Iframe content is:", "محتوى iframe هو:",
      [o("une page séparée", "a separate page", "صفحة منفصلة"), o("des li de ta page", "li from your page", "li من صفحتك"), o("ton head mélangé", "your mixed head", "head مخلوط"), o("un commentaire", "a comment", "تعليق")], 0, "Document autre.", "Another document.", "مستند آخر."),
    Q("Intégrer YouTube sans iframe :", "Embedding YouTube without iframe:",
      "تضمين يوتيوب بدون iframe:",
      [o("pas la méthode vue en cours", "not the method seen in class", "ليست طريقة الدرس"), o("avec ul seulement", "with ul only", "بـ ul فقط"), o("avec br seulement", "with br only", "بـ br فقط"), o("avec sub", "with sub", "بـ sub")], 0, "YouTube donne un iframe.", "YouTube gives an iframe.", "يوتيوب يعطي iframe."),
],
[
    P(("iframe local 500×280.", "local iframe 500×280.", "iframe محلي 500×280."), "", "<iframe src=\"../chapitre-10/index.html\" width=\"500\" height=\"280\" title=\"Audio\"></iframe>", ("src local", "local src", "src محلي")),
    P(("Ajoute title.", "Add title.", "أضف title."), "<iframe src=\"page.html\"></iframe>", "<iframe src=\"page.html\" title=\"Aperçu de la page\"></iframe>", ("title", "title", "title")),
    P(("YouTube embed.", "YouTube embed.", "تضمين يوتيوب."), "", "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/U2-JPqrALsA\" title=\"YouTube\" allowfullscreen></iframe>", ("embed", "embed", "embed")),
    P(("Corrige watch?v= en embed.", "Fix watch?v= into embed.", "صحّح watch?v= إلى embed."), "<iframe src=\"https://www.youtube.com/watch?v=U2-JPqrALsA\"></iframe>", "<iframe src=\"https://www.youtube.com/embed/U2-JPqrALsA\" title=\"YouTube\"></iframe>", ("/embed/", "/embed/", "/embed/")),
    P(("allowfullscreen.", "allowfullscreen.", "allowfullscreen."), "<iframe src=\"https://www.youtube.com/embed/U2-JPqrALsA\"></iframe>", "<iframe src=\"https://www.youtube.com/embed/U2-JPqrALsA\" allowfullscreen title=\"YouTube\"></iframe>", ("allowfullscreen", "allowfullscreen", "allowfullscreen")),
    P(("width 560 height 315.", "width 560 height 315.", "width 560 height 315."), "<iframe src=\"https://www.youtube.com/embed/U2-JPqrALsA\"></iframe>", "<iframe src=\"https://www.youtube.com/embed/U2-JPqrALsA\" width=\"560\" height=\"315\" title=\"YouTube\"></iframe>", ("taille YT.", "YT size.", "حجم YT.")),
    P(("loading lazy.", "loading lazy.", "loading lazy."), "<iframe src=\"page.html\" title=\"p\"></iframe>", "<iframe src=\"page.html\" title=\"p\" loading=\"lazy\"></iframe>", ("lazy", "lazy", "lazy")),
    P(("h2 + iframe local.", "h2 + local iframe.", "h2 + iframe محلي."), "", "<h2>Aperçu chapitre 10</h2>\n<iframe src=\"../chapitre-10/index.html\" title=\"Audio\" width=\"500\" height=\"280\"></iframe>", ("exemple cours.", "course example.", "مثال الدرس.")),
    P(("Corrige video pour YouTube.", "Fix video used for YouTube.", "صحّح video المستخدم ليوتيوب."), "<video src=\"https://www.youtube.com/watch?v=U2-JPqrALsA\" controls></video>", "<iframe src=\"https://www.youtube.com/embed/U2-JPqrALsA\" title=\"YouTube\" allowfullscreen></iframe>", ("iframe embed", "iframe embed", "iframe embed")),
    P(("Corrige href sur iframe.", "Fix href on iframe.", "صحّح href على iframe."), "<iframe href=\"page.html\"></iframe>", "<iframe src=\"page.html\" title=\"page\"></iframe>", ("src", "src", "src")),
    P(("Deux iframes : local + YT.", "Two iframes: local + YT.", "iframeان: محلي + YT."), "", "<iframe src=\"../chapitre-10/index.html\" title=\"Local\" width=\"400\" height=\"200\"></iframe>\n<iframe src=\"https://www.youtube.com/embed/U2-JPqrALsA\" title=\"YouTube\" width=\"400\" height=\"200\"></iframe>", ("deux cadres.", "two frames.", "إطاران.")),
    P(("allow copié YouTube (autoplay…).", "copied YouTube allow.", "allow المنسوخ من يوتيوب."), "<iframe src=\"https://www.youtube.com/embed/U2-JPqrALsA\"></iframe>", "<iframe src=\"https://www.youtube.com/embed/U2-JPqrALsA\" title=\"YouTube\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", ("allow", "allow", "allow")),
    P(("article + iframe.", "article + iframe.", "article + iframe."), "", "<article>\n<h3>Tutoriel</h3>\n<iframe src=\"https://www.youtube.com/embed/U2-JPqrALsA\" title=\"Tuto\" width=\"560\" height=\"315\"></iframe>\n</article>", ("conteneur", "container", "حاوية")),
    P(("title FR descriptif.", "descriptive FR title.", "title وصفي بالفرنسية."), "<iframe src=\"page.html\"></iframe>", "<iframe src=\"page.html\" title=\"Aperçu de la fiche audio du chapitre 10\"></iframe>", ("décrire", "describe", "صف")),
    P(("Taille 400×250 fichier local.", "Size 400×250 local file.", "حجم 400×250 ملف محلي."), "<iframe src=\"../chapitre-9/index.html\"></iframe>", "<iframe src=\"../chapitre-9/index.html\" width=\"400\" height=\"250\" title=\"Vidéo chapitre 9\"></iframe>", ("chapitre 9", "chapter 9", "الفصل 9")),
    P(("Ne pas oublier la balise fermante iframe.", "Do not forget the iframe closing tag.", "لا تنسَ وسم إغلاق iframe."), "<iframe src=\"page.html\" title=\"p\">", "<iframe src=\"page.html\" title=\"p\"></iframe>", ("</iframe>", "</iframe>", "</iframe>")),
    P(("p d’explication + iframe.", "explanation p + iframe.", "فقرة شرح + iframe."), "", "<p>Je suis dans le chapitre 11.</p>\n<iframe src=\"../chapitre-10/index.html\" title=\"Audio\" width=\"500\" height=\"280\"></iframe>", ("comme index.html", "like index.html", "مثل index.html")),
    P(("referrerpolicy (YT).", "referrerpolicy (YT).", "referrerpolicy (YT)."), "<iframe src=\"https://www.youtube.com/embed/U2-JPqrALsA\" title=\"YT\"></iframe>", "<iframe src=\"https://www.youtube.com/embed/U2-JPqrALsA\" title=\"YT\" referrerpolicy=\"strict-origin-when-cross-origin\"></iframe>", ("copié YT", "copied YT", "منسوخ YT")),
    P(("Mini page 11 : h1 + 2 sections iframe.", "Mini page 11: h1 + 2 iframe sections.", "صفحة 11: h1 + قسمان iframe."), "", "<h1>Iframe</h1>\n<h2>Local</h2>\n<iframe src=\"../chapitre-10/index.html\" title=\"Local\" width=\"500\" height=\"200\"></iframe>\n<h2>YouTube</h2>\n<iframe src=\"https://www.youtube.com/embed/U2-JPqrALsA\" title=\"YouTube\" width=\"500\" height=\"200\" allowfullscreen></iframe>", ("les 2 usages.", "both uses.", "الاستخدامان.")),
    P(("sandbox allow-scripts (aperçu doc).", "sandbox allow-scripts (docs preview).", "sandbox allow-scripts (معاينة التوثيق)."), "<iframe src=\"page.html\" title=\"p\"></iframe>", "<iframe src=\"page.html\" title=\"p\" sandbox=\"allow-scripts allow-same-origin\"></iframe>", ("sécurité", "security", "أمان")),
])

make_ch("chapitre-12", "chapitre-12.md", T("Chapitre 12 — HTML Head", "Chapter 12 — HTML Head", "الفصل 12 — HTML Head"),
[
    Q("head contient :", "head contains:", "head يحتوي:",
      [o("la configuration (peu visible)", "configuration (barely visible)", "الإعدادات (شبه غير ظاهرة)"), o("tout le texte h1 de la page seulement", "all h1 page text only", "كل نص h1 فقط"), o("uniquement des li", "li only", "li فقط"), o("uniquement des video", "video only", "video فقط")], 0, "body = visible.", "body = visible.", "body = الظاهر."),
    Q("charset UTF-8 :", "charset UTF-8:", "charset UTF-8:",
      [o("accents, €, emojis", "accents, €, emojis", "الحركات و € والإيموجي"), o("une liste ol", "an ol list", "قائمة ol"), o("un iframe", "an iframe", "iframe"), o("un footer", "a footer", "footer")], 0, "Première meta souvent.", "Often the first meta.", "أول meta غالبًا."),
    Q("viewport :", "viewport:", "viewport:",
      [o("largeur écran (téléphone vs PC)", "screen width (phone vs PC)", "عرض الشاشة (هاتف مقابل حاسوب)"), o("un type mp3", "an mp3 type", "نوع mp3"), o("un dt", "a dt", "dt"), o("un mark", "a mark", "mark")], 0, "width=device-width.", "width=device-width.", "width=device-width."),
    Q("Sans viewport le téléphone :", "Without viewport the phone:", "بدون viewport الهاتف:",
      [o("affiche souvent une mini page PC", "often shows a tiny desktop page", "يعرض غالبًا صفحة حاسوب مصغّرة"), o("lit un mp4 tout seul", "plays an mp4 alone", "يشغّل mp4 وحده"), o("crée un ul", "creates a ul", "ينشئ ul"), o("ajoute un favicon", "adds a favicon", "يضيف أيقونة تبويب")], 0, "Zoom pénible.", "Painful zoom.", "تكبير مزعج."),
    Q("title va dans :", "title goes in:", "title يوضع في:",
      [o("head", "head", "head"), o("body seulement", "body only", "body فقط"), o("footer", "footer", "footer"), o("source", "source", "source")], 0, "Onglet.", "Tab.", "التبويب."),
    Q("favicon :", "favicon:", "أيقونة التبويب:",
      [o("link dans head", "link in head", "link في head"), o("ol dans body", "ol in body", "ol في body"), o("audio", "audio", "audio"), o("iframe YT", "YT iframe", "iframe يوتيوب")], 0, "Chapitre 4 + 12.", "Chapters 4 + 12.", "الفصلان 4 و 12."),
    Q("CSS externe :", "External CSS:", "CSS خارجي:",
      [o("link rel=\"stylesheet\" href=\"style.css\"", "link rel=\"stylesheet\" href=\"style.css\"", "link rel=\"stylesheet\" href=\"style.css\""), o("img src style.css", "img src style.css", "img src style.css"), o("audio src style.css", "audio src style.css", "audio src style.css"), o("ul href style.css", "ul href style.css", "ul href style.css")], 0, "Dans head souvent.", "Often in head.", "في head غالبًا."),
    Q("JS librairie icônes :", "JS icon library:", "مكتبة أيقونات JS:",
      [o("script src dans head (Akar)", "script src in head (Akar)", "script src في head (Akar)"), o("un dt", "a dt", "dt"), o("un hr", "an hr", "hr"), o("un sub", "a sub", "sub")], 0, "Chapitre 7.", "Chapter 7.", "الفصل 7."),
    Q("meta description :", "meta description:", "meta description:",
      [o("texte pour Google sous le titre", "text for Google under the title", "نص لجوجل تحت العنوان"), o("un h1 visible grand", "a large visible h1", "h1 ظاهر كبير"), o("un ol", "an ol", "ol"), o("un source mp4", "an mp4 source", "source mp4")], 0, "SEO.", "SEO.", "SEO."),
    Q("style interne :", "Internal style:", "style داخلي:",
      [o("<style> dans head", "<style> in head", "<style> في head"), o("<ul> dans charset", "<ul> in charset", "<ul> في charset"), o("<br> CSS", "<br> CSS", "<br> CSS"), o("<video> CSS", "<video> CSS", "<video> CSS")], 0, "CSS dans la page.", "CSS in the page.", "CSS في الصفحة."),
    Q("JS peut aussi aller :", "JS can also go:", "يمكن لـ JS أن يذهب:",
      [o("avant </body> (souvent mieux)", "before </body> (often better)", "قبل </body> (أفضل غالبًا)"), o("dans alt d’img seulement", "in img alt only", "في alt لـ img فقط"), o("dans un li obligatoire", "in a required li", "في li إلزامي"), o("dans DOCTYPE", "in DOCTYPE", "في DOCTYPE")], 0, "Vitesse.", "Speed.", "السرعة."),
    Q("lang=\"fr\" se met sur :", "lang=\"fr\" goes on:", "lang=\"fr\" توضع على:",
      [o("html", "html", "html"), o("source", "source", "source"), o("hr", "hr", "hr"), o("br", "br", "br")], 0, "Langue du document.", "Document language.", "لغة المستند."),
    Q("meta author :", "meta author:", "meta author:",
      [o("nom de l’auteur", "author name", "اسم المؤلف"), o("un iframe", "an iframe", "iframe"), o("un ol", "an ol", "ol"), o("un emoji obligatoire", "a required emoji", "إيموجي إلزامي")], 0, "Optionnel.", "Optional.", "اختياري."),
    Q("Sans UTF-8 :", "Without UTF-8:", "بدون UTF-8:",
      [o("é et 😀 peuvent casser", "é and 😀 can break", "é و 😀 قد ينكسران"), o("ol disparaît", "ol disappears", "ol يختفي"), o("video devient audio", "video becomes audio", "video يصبح audio"), o("nav devient footer", "nav becomes footer", "nav يصبح footer")], 0, "Chapitre 13 aussi.", "Chapter 13 too.", "الفصل 13 أيضًا."),
    Q("viewport initial-scale=1.0 :", "viewport initial-scale=1.0:", "viewport initial-scale=1.0:",
      [o("pas de zoom bizarre au départ", "no weird initial zoom", "بدون تكبير غريب في البداية"), o("crée 1.0 listes", "creates 1.0 lists", "ينشئ 1.0 قائمة"), o("est un mp3", "is an mp3", "mp3"), o("est un article", "is an article", "article")], 0, "Échelle 1.", "Scale 1.", "مقياس 1."),
    Q("On voit le title :", "We see title:", "نرى title:",
      [o("dans l’onglet, pas comme h1", "in the tab, not as h1", "في التبويب لا كـ h1"), o("en grand dans body automatiquement", "large in body automatically", "كبيرًا في body تلقائيًا"), o("dans un ul", "in a ul", "في ul"), o("dans audio", "in audio", "في audio")], 0, "Rappel ch.4.", "Ch.4 reminder.", "تذكير الفصل 4."),
    Q("link est vide :", "link is empty:", "link فارغ:",
      [o("oui (favicon, CSS)", "yes (favicon, CSS)", "نعم (أيقونة، CSS)"), o("non, </link> obligatoire", "no, </link> required", "لا، </link> إلزامي"), o("c’est un p", "it is a p", "إنه p"), o("c’est un h2", "it is an h2", "إنه h2")], 0, "Void.", "Void.", "فارغ."),
    Q("meta est vide :", "meta is empty:", "meta فارغ:",
      [o("oui", "yes", "نعم"), o("non", "no", "لا"), o("c’est un iframe", "it is an iframe", "إنه iframe"), o("c’est un dl", "it is a dl", "إنه dl")], 0, "Pas de </meta>.", "No </meta>.", "لا </meta>."),
    Q("Ordre conseillé :", "Suggested order:", "ترتيب مستحسن:",
      [o("charset, viewport, title, favicon, css, scripts", "charset, viewport, title, favicon, css, scripts", "charset ثم viewport ثم title ثم الأيقونة ثم css ثم السكربتات"), o("body puis head", "body then head", "body ثم head"), o("footer puis doctype", "footer then doctype", "footer ثم doctype"), o("ul puis html", "ul then html", "ul ثم html")], 0, "Lisibilité.", "Readability.", "وضوح."),
    Q("head n’affiche pas :", "head does not display:", "head لا يعرض:",
      [o("le h1, les p, les images du site (ça c’est body)", "the site h1, p, images (that is body)", "h1 والفقرات والصور (ذلك body)"), o("jamais le title d’onglet", "never the tab title", "عنوان التبويب أبدًا"), o("jamais le favicon", "never the favicon", "الأيقونة أبدًا"), o("la config", "the config", "الإعداد")], 0, "Visible vs config.", "Visible vs config.", "ظاهر مقابل إعداد."),
],
[
    P(("meta charset.", "meta charset.", "meta charset."), "<head></head>", "<head>\n<meta charset=\"UTF-8\">\n</head>", ("UTF-8", "UTF-8", "UTF-8")),
    P(("viewport.", "viewport.", "viewport."), "<head>\n<meta charset=\"UTF-8\">\n</head>", "<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n</head>", ("viewport", "viewport", "viewport")),
    P(("title.", "title.", "title."), "<head></head>", "<head>\n<title>Annonces Alger | Aboni</title>\n</head>", ("title", "title", "title")),
    P(("favicon.", "favicon.", "أيقونة."), "<head>\n<title>X</title>\n</head>", "<head>\n<title>X</title>\n<link rel=\"shortcut icon\" href=\"icones/html.png\" type=\"image/png\">\n</head>", ("link", "link", "link")),
    P(("CSS externe.", "External CSS.", "CSS خارجي."), "<head></head>", "<head>\n<link rel=\"stylesheet\" href=\"style.css\">\n</head>", ("stylesheet", "stylesheet", "stylesheet")),
    P(("script Akar.", "Akar script.", "سكربت Akar."), "<head></head>", "<head>\n<script src=\"https://unpkg.com/akar-icons-fonts\"></script>\n</head>", ("script", "script", "script")),
    P(("meta description.", "meta description.", "meta description."), "<head></head>", "<head>\n<meta name=\"description\" content=\"Mini site d'annonces à Alger.\">\n</head>", ("description", "description", "description")),
    P(("style interne body font.", "internal style body font.", "style داخلي لخط body."), "<head></head>", "<head>\n<style>body { font-family: sans-serif; }</style>\n</head>", ("style", "style", "style")),
    P(("lang fr sur html.", "lang fr on html.", "lang fr على html."), "<html>\n<head></head>\n</html>", "<html lang=\"fr\">\n<head></head>\n</html>", ("lang", "lang", "lang")),
    P(("author Aboni.", "author Aboni.", "author Aboni."), "<head></head>", "<head>\n<meta name=\"author\" content=\"Aboni\">\n</head>", ("author", "author", "author")),
    P(("Head complet du cours.", "Full course head.", "head كامل للدرس."), "<head></head>", "<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n<meta name=\"description\" content=\"Cours HTML\">\n<title>Chapitre 12 | Aboni</title>\n<link rel=\"shortcut icon\" href=\"icones/html.png\" type=\"image/png\">\n</head>", ("toutes les lignes.", "all lines.", "كل الأسطر.")),
    P(("Corrige title dans body.", "Fix title in body.", "صحّح title في body."), "<body><title>X</title><h1>X</h1></body>", "<head><title>X</title></head>\n<body><h1>X</h1></body>", ("head", "head", "head")),
    P(("Test UTF-8 dans body.", "UTF-8 test in body.", "اختبار UTF-8 في body."), "<head><meta charset=\"UTF-8\"></head>\n<body></body>", "<head><meta charset=\"UTF-8\"></head>\n<body><p>café 85 € 😀 🇩🇿</p></body>", ("accents emoji", "accents emoji", "حركات وإيموجي")),
    P(("CSS + title.", "CSS + title.", "CSS + title."), "<head></head>", "<head>\n<title>Site</title>\n<link rel=\"stylesheet\" href=\"style.css\">\n</head>", ("2 liens config.", "2 config links.", "رابطا إعداد.")),
    P(("script avant fin body.", "script before end body.", "script قبل نهاية body."), "<body>\n<h1>Hi</h1>\n</body>", "<body>\n<h1>Hi</h1>\n<script src=\"app.js\"></script>\n</body>", ("fin body", "end body", "نهاية body")),
    P(("viewport content exact.", "exact viewport content.", "محتوى viewport الدقيق."), "<meta name=\"viewport\">", "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">", ("content", "content", "content")),
    P(("Deux meta + title.", "Two meta + title.", "metaان + title."), "", "<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n<title>Aboni</title>\n</head>", ("base", "base", "أساس")),
    P(("Commentaires dans head.", "Comments in head.", "تعليقات في head."), "<head>\n<title>X</title>\n</head>", "<head>\n<!-- configuration -->\n<title>X</title>\n</head>", ("<!-- -->", "<!-- -->", "<!-- -->")),
    P(("Ne pas mettre h1 dans head.", "Do not put h1 in head.", "لا تضع h1 في head."), "<head><h1>Annonces</h1></head>", "<head><title>Annonces</title></head>\n<body><h1>Annonces</h1></body>", ("h1 → body", "h1 → body", "h1 → body")),
    P(("Page minimale valide cours.", "Minimal valid course page.", "صفحة دنيا صالحة للدرس."), "", "<!DOCTYPE html>\n<html lang=\"fr\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n<title>Aboni</title>\n</head>\n<body>\n<h1>Hello</h1>\n</body>\n</html>", ("squelette", "skeleton", "هيكل")),
])

make_ch("chapitre-13", "chapitre-13.md", T("Chapitre 13 — Symboles et emojis", "Chapter 13 — Symbols and emojis", "الفصل 13 — الرموز والإيموجي"),
[
    Q("Pour coller 😀 il faut :", "To paste 😀 you need:", "للصق 😀 تحتاج:",
      [o("meta charset UTF-8", "meta charset UTF-8", "meta charset UTF-8"), o("un ol", "an ol", "ol"), o("un iframe", "an iframe", "iframe"), o("controls", "controls", "controls")], 0, "Sinon caractères cassés.", "Otherwise broken characters.", "وإلا محارف مكسورة."),
    Q("Une entity commence par :", "An entity starts with:", "يبدأ الكيان بـ:",
      [o("& et finit par ;", "& and ends with ;", "& وينتهي بـ ;"), o("< seulement", "< only", "< فقط"), o("//", "//", "//"), o("<!--", "<!--", "<!--")], 0, "&copy;", "&copy;", "&copy;"),
    Q("&lt; affiche :", "&lt; displays:", "&lt; يعرض:",
      [o("<", "<", "<"), o(">", ">", ">"), o("&", "&", "&"), o("©", "©", "©")], 0, "less than.", "less than.", "أقل من."),
    Q("&gt; affiche :", "&gt; displays:", "&gt; يعرض:",
      [o(">", ">", ">"), o("<", "<", "<"), o("€", "€", "€"), o("♥", "♥", "♥")], 0, "greater than.", "greater than.", "أكبر من."),
    Q("&amp; affiche :", "&amp; displays:", "&amp; يعرض:",
      [o("&", "&", "&"), o("<", "<", "<"), o("©", "©", "©"), o("½", "½", "½")], 0, "Sinon & commence une entity.", "Otherwise & starts an entity.", "وإلا & يبدأ كيانًا."),
    Q("&nbsp; :", "&nbsp;:", "&nbsp;:",
      [o("espace insécable / forcé", "non-breaking / forced space", "مسافة غير قابلة للكسر / إجبارية"), o("un saut de page PDF", "a PDF page break", "فاصل صفحة PDF"), o("une video", "a video", "فيديو"), o("un header", "a header", "header")], 0, "250 000 DA sans coupure.", "250 000 DA without wrapping.", "250 000 دج بلا قطع."),
    Q("&copy; :", "&copy;:", "&copy;:",
      [o("©", "©", "©"), o("€", "€", "€"), o("<", "<", "<"), o("😀", "😀", "😀")], 0, "Copyright.", "Copyright.", "حقوق."),
    Q("&euro; :", "&euro;:", "&euro;:",
      [o("€", "€", "€"), o("$", "$", "$"), o("©", "©", "©"), o("→", "→", "→")], 0, "Euro.", "Euro.", "يورو."),
    Q("&#169; et &copy; :", "&#169; and &copy;:", "&#169; و &copy;:",
      [o("le même © (numéro vs nom)", "the same © (number vs name)", "نفس © (رقم مقابل اسم)"), o("deux symboles opposés", "two opposite symbols", "رمزان متعاكسان"), o("un ol et un ul", "an ol and a ul", "ol و ul"), o("audio et video", "audio and video", "audio و video")], 0, "Deux écritures.", "Two writings.", "كتابتان."),
    Q("&#128512; :", "&#128512;:", "&#128512;:",
      [o("😀", "😀", "😀"), o("©", "©", "©"), o("<p>", "<p>", "<p>"), o("un iframe", "an iframe", "iframe")], 0, "Code emoji.", "Emoji code.", "رمز إيموجي."),
    Q("Pourquoi &lt;p&gt; ?", "Why &lt;p&gt;?", "لماذا &lt;p&gt;؟",
      [o("afficher la balise comme texte, pas l’interpréter", "show the tag as text, not interpret it", "عرض الوسم كنص لا تفسيره"), o("créer un vrai p", "create a real p", "إنشاء p حقيقي"), o("lire un mp3", "play an mp3", "تشغيل mp3"), o("ouvrir YouTube", "open YouTube", "فتح يوتيوب")], 0, "Caractères réservés.", "Reserved characters.", "محارف محجوزة."),
    Q("Plusieurs espaces HTML :", "Several HTML spaces:", "عدة مسافات HTML:",
      [o("deviennent un seul ; d’où &nbsp;", "become one; hence &nbsp;", "تصبح واحدة؛ لذلك &nbsp;"), o("sont toujours gardés", "are always kept", "تُحفظ دائمًا"), o("créent des ol", "create ol", "تنشئ ol"), o("cassent charset", "break charset", "تكسر charset")], 0, "Règle HTML.", "HTML rule.", "قاعدة HTML."),
    Q("&quot; :", "&quot;:", "&quot;:",
      [o("\"", "\"", "\""), o("'", "'", "'"), o("<", "<", "<"), o("©", "©", "©")], 0, "Guillemet.", "Quote.", "علامة اقتباس."),
    Q("Coller 🇩🇿 direct :", "Pasting 🇩🇿 directly:", "لصق 🇩🇿 مباشرة:",
      [o("OK avec UTF-8", "OK with UTF-8", "جائز مع UTF-8"), o("interdit", "forbidden", "ممنوع"), o("besoin de ol", "needs ol", "يحتاج ol"), o("besoin de video", "needs video", "يحتاج video")], 0, "Méthode simple.", "Simple method.", "طريقة بسيطة."),
    Q("&times; :", "&times;:", "&times;:",
      [o("×", "×", "×"), o("÷", "÷", "÷"), o("€", "€", "€"), o("<", "<", "<")], 0, "Multiplication.", "Multiplication.", "ضرب."),
    Q("&ge; :", "&ge;:", "&ge;:",
      [o("≥", "≥", "≥"), o("≤", "≤", "≤"), o("≠", "≠", "≠"), o("©", "©", "©")], 0, "Plus grand ou égal.", "Greater or equal.", "أكبر أو يساوي."),
    Q("Le numéro marche :", "The number works:", "الرقم يعمل:",
      [o("même si le nom d’entity n’existe pas (emojis)", "even if the entity name does not exist (emojis)", "حتى إن لم يوجد اسم الكيان (إيموجي)"), o("seulement pour ol", "only for ol", "لـ ol فقط"), o("seulement sans UTF-8", "only without UTF-8", "بدون UTF-8 فقط"), o("jamais", "never", "أبدًا")], 0, "&#128512;", "&#128512;", "&#128512;"),
    Q("&hearts; :", "&hearts;:", "&hearts;:",
      [o("♥", "♥", "♥"), o("©", "©", "©"), o("→", "→", "→"), o("<", "<", "<")], 0, "Cœur.", "Heart.", "قلب."),
    Q("Sans ; à la fin de &copy :", "Without ; at the end of &copy:", "بدون ; في نهاية &copy:",
      [o("l’entity peut échouer", "the entity may fail", "قد يفشل الكيان"), o("c’est mieux", "it is better", "أفضل"), o("ça crée un iframe", "it creates an iframe", "ينشئ iframe"), o("ça lit un mp4", "it plays an mp4", "يشغّل mp4")], 0, "Toujours &...;", "Always &...;", "دائمًا &...;"),
    Q("Les plus utilisés en cours :", "The most used in class:", "الأكثر استخدامًا في الدرس:",
      [o("&copy; &euro; &amp; &lt; &gt; &nbsp;", "&copy; &euro; &amp; &lt; &gt; &nbsp;", "&copy; &euro; &amp; &lt; &gt; &nbsp;"), o("seulement ol li", "ol li only", "ol li فقط"), o("seulement source type", "source type only", "source type فقط"), o("seulement target blank", "target blank only", "target blank فقط")], 0, "À retenir.", "Remember.", "للتذكر."),
],
[
    P(("Emoji collé.", "Pasted emoji.", "إيموجي ملصوق."), "<p>bonjour</p>", "<p>bonjour 😀</p>", ("coller", "paste", "الصق")),
    P(("Code 128512.", "Code 128512.", "الرمز 128512."), "<p></p>", "<p>&#128512;</p>", ("&#", "&#", "&#")),
    P(("Copyright nom.", "Copyright name.", "حقوق بالاسم."), "<p>2026 Aboni</p>", "<p>&copy; 2026 Aboni</p>", ("&copy;", "&copy;", "&copy;")),
    P(("Euro.", "Euro.", "يورو."), "<p>2500</p>", "<p>2500 &euro;</p>", ("&euro;", "&euro;", "&euro;")),
    P(("Afficher <p></p> comme texte.", "Show <p></p> as text.", "اعرض <p></p> كنص."), "<p>l'element p s'ecrit p</p>", "<p>l'element p s'ecrit &lt;p&gt;&lt;/p&gt;</p>", ("lt gt", "lt gt", "lt gt")),
    P(("&amp; pour &.", "&amp; for &.", "&amp; من أجل &."), "<p>HTML CSS</p>", "<p>HTML &amp; CSS</p>", ("amp", "amp", "amp")),
    P(("nbsp dans le prix.", "nbsp in the price.", "nbsp في السعر."), "<p>85 000 DA</p>", "<p>85&nbsp;000&nbsp;DA</p>", ("nbsp", "nbsp", "nbsp")),
    P(("© par numéro.", "© by number.", "© بالرقم."), "<p></p>", "<p>&#169;</p>", ("169", "169", "169")),
    P(("Algérie emoji.", "Algeria emoji.", "إيموجي الجزائر."), "<p>Alger</p>", "<p>Alger 🇩🇿</p>", ("UTF-8", "UTF-8", "UTF-8")),
    P(("≥ 9/10.", "≥ 9/10.", "≥ 9/10."), "<p>Note 9/10</p>", "<p>Note &ge; 9/10</p>", ("ge", "ge", "ge")),
    P(("m² entity ou sup.", "m² entity or sup.", "م² كيان أو sup."), "<p>85 m2</p>", "<p>85 m&sup2;</p>", ("sup2", "sup2", "sup2")),
    P(("flèche droite.", "right arrow.", "سهم يمين."), "<p>Voir annonce</p>", "<p>Voir annonce &rarr;</p>", ("rarr", "rarr", "rarr")),
    P(("cœur.", "heart.", "قلب."), "<p>Favori</p>", "<p>Favori &hearts;</p>", ("hearts", "hearts", "hearts")),
    P(("guillemets entity.", "quote entity.", "كيان اقتباس."), "<p>ok</p>", "<p>&quot;ok&quot;</p>", ("quot", "quot", "quot")),
    P(("demi ½.", "half ½.", "النصف ½."), "<p>1/2</p>", "<p>&frac12;</p>", ("frac12", "frac12", "frac12")),
    P(("pied d’annonce complet.", "full listing footer.", "تذييل إعلان كامل."), "", "<p>Prix : 85&nbsp;000 DA</p>\n<p>&copy; 2026 Aboni — Alger 🇩🇿</p>", ("nbsp copy emoji", "nbsp copy emoji", "nbsp و copy وإيموجي")),
    P(("tableau 2 entities.", "table of 2 entities.", "جدول كيانين."), "", "<p>&copy; = &#169;</p>\n<p>&euro;</p>", ("nom + numéro", "name + number", "اسم + رقم")),
    P(("Corrige < brut dans le texte.", "Fix raw < in the text.", "صحّح < الخام في النص."), "<p>balise <p></p>", "<p>balise &lt;p&gt;</p>", ("lt", "lt", "lt")),
    P(("times multiplication.", "times multiplication.", "times للضرب."), "<p>3 x 4</p>", "<p>3 &times; 4</p>", ("times", "times", "times")),
    P(("Phrase cours : UTF-8 + entity + emoji.", "Course sentence: UTF-8 + entity + emoji.", "جملة الدرس: UTF-8 + كيان + إيموجي."), "", "<p>bonjour 😀 — l'élément s'écrit &lt;p&gt; — &copy; 2026</p>", ("tout le chapitre.", "the whole chapter.", "الفصل كله.")),
])
print("ch11-13 ok")
