# -*- coding: utf-8 -*-
"""Chapters 2–13 exercise banks. Imported by gen_all.py"""
from gen_exos import T, Q, P, o, make_ch

# Chapter 2
make_ch("chapitre-2", "chapitre-2.md", T("Chapitre 2 — Mise en forme", "Chapter 2 — Formatting", "الفصل 2 — التنسيق"),
[
    Q("Quelle balise met en gras ?", "Which tag makes text bold?", "أي وسم يجعل النص غامقًا؟",
      [o("i", "i", "i"), o("b", "b", "b"), o("u", "u", "u"), o("p", "p", "p")], 1, "b (ou strong).", "b (or strong).", "b (أو strong)."),
    Q("i affiche le texte :", "i displays text:", "i يعرض النص:",
      [o("souligné", "underlined", "مسطرًا"), o("en italique", "in italic", "مائلًا"), o("surligné", "highlighted", "مميزًا"), o("en exposant", "as superscript", "كأس")], 1, "i = italic.", "i = italic.", "i = مائل."),
    Q("mark sert à :", "mark is used to:", "mark يُستخدم لـ:",
      [o("surligner", "highlight", "تمييز"), o("une vidéo", "a video", "فيديو"), o("un lien", "a link", "رابط"), o("un saut de ligne", "a line break", "سطر جديد")], 0, "Surlignage jaune par défaut.", "Default yellow highlight.", "تمييز أصفر افتراضيًا."),
    Q("sub place le texte :", "sub places text:", "sub يضع النص:",
      [o("en haut", "higher", "أعلى"), o("en bas (indice)", "lower (subscript)", "أسفل"), o("au centre", "in the center", "في الوسط"), o("caché", "hidden", "مخفيًا")], 1, "H2O → H<sub>2</sub>O.", "H2O → H<sub>2</sub>O.", "H2O → H<sub>2</sub>O."),
    Q("sup place le texte :", "sup places text:", "sup يضع النص:",
      [o("en exposant", "as superscript", "كأس"), o("en indice", "as subscript", "كمنخفض"), o("en bloc", "as a block", "ككتلة"), o("dans head", "in head", "في head")], 0, "m², 3e étage.", "m², 3rd floor.", "م²، الطابق 3."),
    Q("u sert à :", "u is for:", "u لـ:",
      [o("souligner", "underline", "تسطير"), o("une liste", "a list", "قائمة"), o("un iframe", "an iframe", "iframe"), o("UTF-8", "UTF-8", "UTF-8")], 0, "underline.", "underline.", "تسطير."),
    Q("Ces balises de forme se mettent :", "These formatting tags go:", "وسوم التنسيق تُوضع:",
      [o("à la place de html", "instead of html", "بدل html"), o("à l’intérieur d’un p", "inside a p", "داخل p"), o("seulement dans head", "only in head", "في head فقط"), o("sans balise ouvrante", "without an opening tag", "بلا وسم افتتاحي")], 1, "On entoure un mot dans le paragraphe.", "Wrap a word inside the paragraph.", "نلف كلمة داخل الفقرة."),
    Q("strong est proche de :", "strong is close to:", "strong قريب من:",
      [o("b (gras + importance)", "b (bold + importance)", "b (غامق + أهمية)"), o("img", "img", "img"), o("br", "br", "br"), o("ol", "ol", "ol")], 0, "strong a aussi un sens d’importance.", "strong also carries importance.", "strong يحمل معنى الأهمية أيضًا."),
    Q("em est proche de :", "em is close to:", "em قريب من:",
      [o("i (emphase)", "i (emphasis)", "i (تأكيد)"), o("hr", "hr", "hr"), o("table", "table", "table"), o("source", "source", "source")], 0, "em = emphase.", "em = emphasis.", "em = تأكيد."),
    Q("Pour 85 m² on utilise :", "For 85 m² we use:", "لـ 85 م² نستخدم:",
      [o("sub", "sub", "sub"), o("sup", "sup", "sup"), o("ul", "ul", "ul"), o("audio", "audio", "audio")], 1, "exposant 2.", "superscript 2.", "الأس 2."),
    Q("Pour H2O on utilise :", "For H2O we use:", "لـ H2O نستخدم:",
      [o("sup", "sup", "sup"), o("sub", "sub", "sub"), o("mark", "mark", "mark"), o("u", "u", "u")], 1, "indice 2.", "subscript 2.", "المنخفض 2."),
    Q("On peut combiner :", "We can combine:", "يمكن الجمع بين:",
      [o("b et i autour du même mot", "b and i around the same word", "b و i حول نفس الكلمة"), o("deux DOCTYPE", "two DOCTYPE", "DOCTYPEين"), o("head dans p", "head inside p", "head داخل p"), o("body dans title", "body inside title", "body داخل title")], 0, "<b><i>texte</i></b> est valide.", "<b><i>text</i></b> is valid.", "<b><i>نص</i></b> صالح."),
    Q("Quelle balise n’est PAS de mise en forme de mot ?", "Which is NOT word formatting?", "أي وسم ليس تنسيق كلمة؟",
      [o("b", "b", "b"), o("video", "video", "video"), o("mark", "mark", "mark"), o("u", "u", "u")], 1, "video = média.", "video = media.", "video = وسائط."),
    Q("Le surlignage d’un résultat de recherche ressemble à :", "Search-result highlighting looks like:", "تمييز نتيجة البحث يشبه:",
      [o("mark", "mark", "mark"), o("hr", "hr", "hr"), o("iframe", "iframe", "iframe"), o("meta", "meta", "meta")], 0, "mark.", "mark.", "mark."),
    Q("i à l’origine signifie :", "Originally i means:", "i أصلًا تعني:",
      [o("image", "image", "صورة"), o("italic", "italic", "مائل"), o("iframe", "iframe", "iframe"), o("icon only", "icon only", "أيقونة فقط")], 1, "italic — plus tard réutilisé pour les icônes.", "italic — later reused for icons.", "مائل — ثم أُعيد استخدامه للأيقونات."),
    Q("On évite trop de u parce que :", "We avoid too much u because:", "نتجنب الإكثار من u لأن:",
      [o("ça ressemble à un lien", "it looks like a link", "يشبه الرابط"), o("ça casse UTF-8", "it breaks UTF-8", "يكسر UTF-8"), o("c’est interdit", "it is forbidden", "ممنوع"), o("ça crée un iframe", "it creates an iframe", "ينشئ iframe")], 0, "Le soulignement évoque les liens.", "Underline looks like links.", "التسطير يوحي بالروابط."),
    Q("Pour insister sur un prix on peut :", "To stress a price we can:", "للتأكيد على سعر يمكن:",
      [o("strong", "strong", "strong"), o("source", "source", "source"), o("nav", "nav", "nav"), o("charset", "charset", "charset")], 0, "strong = important.", "strong = important.", "strong = مهم."),
    Q("La mise en forme HTML de base se fait :", "Basic HTML formatting is done:", "تنسيق HTML الأساسي يتم:",
      [o("sans CSS, avec des balises", "without CSS, with tags", "بدون CSS بالوسوم"), o("uniquement en Python", "only in Python", "ببايثون فقط"), o("dans le favicon", "in the favicon", "في أيقونة التبويب"), o("avec audio", "with audio", "بـ audio")], 0, "b, i, u, mark, sub, sup.", "b, i, u, mark, sub, sup.", "b و i و u و mark و sub و sup."),
    Q("un <b> non fermé :", "an unclosed <b>:", "<b> غير مغلق:",
      [o("peut casser l’affichage du texte suivant", "can break the following text display", "قد يفسد عرض النص التالي"), o("crée une vidéo", "creates a video", "ينشئ فيديو"), o("est obligatoire", "is required", "إلزامي"), o("remplace head", "replaces head", "يعوّض head")], 0, "Toujours fermer </b>.", "Always close </b>.", "أغلق دائمًا </b>."),
    Q("3e étage s’écrit bien :", "3rd floor is well written:", "الطابق 3 يُكتب جيدًا:",
      [o("3<sup>e</sup> étage", "3<sup>e</sup> étage", "3<sup>e</sup> étage"), o("3<sub>e</sub> étage", "3<sub>e</sub> étage", "3<sub>e</sub> étage"), o("<video>3e</video>", "<video>3e</video>", "<video>3e</video>"), o("<ul>3e</ul>", "<ul>3e</ul>", "<ul>3e</ul>")], 0, "exposant e.", "superscript e.", "حرف e كأس."),
],
[
    P(("Gras sur F3.", "Bold on F3.", "غامق على F3."), "<p>Appartement F3</p>", "<p>Appartement <b>F3</b></p>", ("b", "b", "b")),
    P(("Italique sur Hydra.", "Italic on Hydra.", "مائل على Hydra."), "<p>à Hydra</p>", "<p>à <i>Hydra</i></p>", ("i", "i", "i")),
    P(("Souligne Visite samedi.", "Underline Visite samedi.", "سطّر Visite samedi."), "<p>Visite samedi</p>", "<p><u>Visite samedi</u></p>", ("u", "u", "u")),
    P(("Surligna Alger.", "Highlight Alger.", "ميّز Alger."), "<p>Ville Alger</p>", "<p>Ville <mark>Alger</mark></p>", ("mark", "mark", "mark")),
    P(("m2 en m².", "m2 into m².", "m2 إلى m²."), "<p>85 m2</p>", "<p>85 m<sup>2</sup></p>", ("sup", "sup", "sup")),
    P(("H2O correct.", "Correct H2O.", "H2O صحيح."), "<p>H2O</p>", "<p>H<sub>2</sub>O</p>", ("sub", "sub", "sub")),
    P(("Prix en strong.", "Price in strong.", "السعر في strong."), "<p>Prix : 85000 DA</p>", "<p>Prix : <strong>85000 DA</strong></p>", ("strong", "strong", "strong")),
    P(("3e avec sup.", "3e with sup.", "3e مع sup."), "<p>3e étage</p>", "<p>3<sup>e</sup> étage</p>", ("sup autour de e.", "sup around e.", "sup حول e.")),
    P(("b et i ensemble.", "b and i together.", "b و i معًا."), "<p>urgent</p>", "<p><b><i>urgent</i></b></p>", ("imbriquer.", "nest them.", "تداخل.")),
    P(("em sur « vraiment ».", "em on “vraiment”.", "em على «vraiment»."), "<p>C'est vraiment bien</p>", "<p>C'est <em>vraiment</em> bien</p>", ("em", "em", "em")),
    P(("Formule CO2.", "Formula CO2.", "صيغة CO2."), "<p>CO2</p>", "<p>CO<sub>2</sub></p>", ("sub", "sub", "sub")),
    P(("Surligna le mot iPhone.", "Highlight the word iPhone.", "ميّز كلمة iPhone."), "<p>Annonce iPhone 13</p>", "<p>Annonce <mark>iPhone</mark> 13</p>", ("mark", "mark", "mark")),
    P(("Gras sur l’état 9/10.", "Bold on condition 9/10.", "غامق على الحالة 9/10."), "<p>État 9/10</p>", "<p>État <b>9/10</b></p>", ("b", "b", "b")),
    P(("Italique nom de ville Oran.", "Italic city name Oran.", "مائل لاسم مدينة وهران."), "<p>à Oran</p>", "<p>à <i>Oran</i></p>", ("i", "i", "i")),
    P(("x2 en exposant.", "x2 as superscript.", "x2 كأس."), "<p>x2</p>", "<p>x<sup>2</sup></p>", ("sup", "sup", "sup")),
    P(("Deux mises en forme : b et mark.", "Two formats: b and mark.", "تنسيقان: b و mark."), "<p>Promo Alger</p>", "<p><b>Promo</b> <mark>Alger</mark></p>", ("deux balises.", "two tags.", "وسمان.")),
    P(("Souligner uniquement samedi.", "Underline only samedi.", "سطّر samedi فقط."), "<p>Visite samedi 10h</p>", "<p>Visite <u>samedi</u> 10h</p>", ("u autour d’un mot.", "u around one word.", "u حول كلمة.")),
    P(("strong + sup dans le même p.", "strong + sup in the same p.", "strong + sup في نفس p."), "<p>Prix 85000 DA - 85 m2</p>", "<p>Prix <strong>85000 DA</strong> - 85 m<sup>2</sup></p>", ("strong et sup.", "strong and sup.", "strong و sup.")),
    P(("Phrase complète d’annonce formatée.", "Fully formatted listing sentence.", "جملة إعلان منسقة بالكامل."), "", "<p>Appartement <b>F3</b> de 85 m<sup>2</sup> à <i>Hydra</i> — <mark>promo</mark>.</p>", ("combine b sup i mark.", "combine b sup i mark.", "اجمع b و sup و i و mark.")),
    P(("Indice et exposant dans la même ligne.", "Sub and sup on the same line.", "منخفض وأس في نفس السطر."), "<p>H2O et m2</p>", "<p>H<sub>2</sub>O et m<sup>2</sup></p>", ("sub et sup.", "sub and sup.", "sub و sup.")),
])
