# -*- coding: utf-8 -*-
from gen_exos import T, Q, P, o, make_ch

make_ch("chapitre-6", "chapitre-6.md", T("Chapitre 6 — Les listes", "Chapter 6 — Lists", "الفصل 6 — القوائم"),
[
    Q("ul signifie :", "ul means:", "ul تعني:",
      [o("unordered list (puces)", "unordered list (bullets)", "قائمة غير مرتبة (نقاط)"), o("unique link", "unique link", "رابط فريد"), o("under line", "under line", "سطر تحت"), o("UTF list", "UTF list", "قائمة UTF")], 0, "Liste à puces.", "Bullet list.", "قائمة نقطية."),
    Q("ol signifie :", "ol means:", "ol تعني:",
      [o("ordered list (numéros)", "ordered list (numbers)", "قائمة مرتبة (أرقام)"), o("old link", "old link", "رابط قديم"), o("open line", "open line", "سطر مفتوح"), o("only list", "only list", "قائمة فقط")], 0, "1. 2. 3.", "1. 2. 3.", "1. 2. 3."),
    Q("Chaque ligne d’un ul/ol est :", "Each row of a ul/ol is:", "كل سطر في ul/ol هو:",
      [o("li (list item)", "li (list item)", "li (عنصر قائمة)"), o("dt", "dt", "dt"), o("source", "source", "source"), o("meta", "meta", "meta")], 0, "li dans ul ou ol.", "li inside ul or ol.", "li داخل ul أو ol."),
    Q("dl est :", "dl is:", "dl هو:",
      [o("description list", "description list", "قائمة وصف"), o("div long", "div long", "div طويل"), o("data link", "data link", "رابط بيانات"), o("dark list", "dark list", "قائمة داكنة")], 0, "Glossaire.", "Glossary.", "قاموس."),
    Q("dt + dd :", "dt + dd:", "dt + dd:",
      [o("terme + définition", "term + definition", "مصطلح + تعريف"), o("deux titres h1", "two h1 titles", "عنوانا h1"), o("audio + video", "audio + video", "صوت + فيديو"), o("head + body", "head + body", "head + body")], 0, "Pas de li dans dl.", "No li in dl.", "لا li في dl."),
    Q("Menu de réseaux sociaux → plutôt :", "Social menu → rather:", "قائمة شبكات → الأفضل:",
      [o("ul", "ul", "ul"), o("ol", "ol", "ol"), o("video", "video", "video"), o("title", "title", "title")], 0, "L’ordre n’est pas une recette.", "Order is not a recipe.", "الترتيب ليس وصفة."),
    Q("Étapes d’achat → plutôt :", "Purchase steps → rather:", "خطوات الشراء → الأفضل:",
      [o("ol", "ol", "ol"), o("span", "span", "span"), o("hr", "hr", "hr"), o("iframe", "iframe", "iframe")], 0, "L’ordre compte.", "Order matters.", "الترتيب مهم."),
    Q("HTML n’est pas une base de données, une liste est :", "HTML is not a database; a list is:", "HTML ليست قاعدة بيانات؛ القائمة هي:",
      [o("une présentation visuelle", "a visual presentation", "عرض بصري"), o("un serveur SQL", "an SQL server", "خادم SQL"), o("un fichier MP4", "an MP4 file", "ملف MP4"), o("un charset", "a charset", "charset")], 0, "Comme Word : puces ou numéros.", "Like Word: bullets or numbers.", "مثل وورد: نقاط أو أرقام."),
    Q("On peut mettre un a dans un li :", "We can put an a inside an li:", "يمكن وضع a داخل li:",
      [o("oui", "yes", "نعم"), o("non", "no", "لا"), o("seulement dans head", "only in head", "في head فقط"), o("seulement avec audio", "only with audio", "مع audio فقط")], 0, "Menu de liens.", "Link menu.", "قائمة روابط."),
    Q("On peut mettre un img dans un li :", "We can put an img inside an li:", "يمكن وضع img داخل li:",
      [o("oui (galerie)", "yes (gallery)", "نعم (معرض)"), o("jamais", "never", "أبدًا"), o("ça casse UTF-8", "it breaks UTF-8", "يكسر UTF-8"), o("seulement en h1", "only in h1", "في h1 فقط")], 0, "Galerie numérotée = ol + img.", "Numbered gallery = ol + img.", "معرض مرقم = ol + img."),
    Q("Sans li, ul :", "Without li, ul:", "بدون li، ul:",
      [o("est incorrect / incomplet", "is incorrect / incomplete", "غير صحيح / ناقص"), o("devient une video", "becomes a video", "يصبح فيديو"), o("est un favicon", "is a favicon", "أيقونة تبويب"), o("remplace main", "replaces main", "يعوّض main")], 0, "ul contient des li.", "ul contains li.", "ul يحتوي li."),
    Q("Imbriquer une liste :", "Nesting a list:", "تداخل قائمة:",
      [o("ul dans un li", "ul inside an li", "ul داخل li"), o("ul dans head", "ul in head", "ul في head"), o("li dans title onglet", "li in the tab title", "li في عنوان التبويب"), o("ol dans charset", "ol in charset", "ol في charset")], 0, "Sous-liste.", "Sub-list.", "قائمة فرعية."),
    Q("Wilayas (Alger, Oran…) :", "Wilayas (Alger, Oran…):", "ولايات (الجزائر، وهران…):",
      [o("ul", "ul", "ul"), o("ol si le rang compte (classement)", "ol if rank matters", "ol إن كان الترتيب مهمًا"), o("les deux selon le besoin", "both depending on need", "كلاهما حسب الحاجة"), o("iframe seulement", "iframe only", "iframe فقط")], 2, "Puces ou classement.", "Bullets or ranking.", "نقاط أو ترتيب."),
    Q("dt veut dire :", "dt means:", "dt تعني:",
      [o("description term", "description term", "مصطلح الوصف"), o("div title", "div title", "عنوان div"), o("data table", "data table", "جدول بيانات"), o("dark theme", "dark theme", "مظهر داكن")], 0, "Le mot.", "The word.", "الكلمة."),
    Q("dd veut dire :", "dd means:", "dd تعني:",
      [o("description (définition)", "description (definition)", "الوصف (التعريف)"), o("document data", "document data", "بيانات المستند"), o("doctype default", "doctype default", "doctype افتراضي"), o("drag drop", "drag drop", "سحب وإفلات")], 0, "L’explication du dt.", "The explanation of dt.", "شرح dt."),
    Q("Glossaire HTML / CSS / JS → :", "HTML / CSS / JS glossary →", "قاموس HTML / CSS / JS →",
      [o("dl", "dl", "dl"), o("video", "video", "video"), o("img", "img", "img"), o("br seulement", "br only", "br فقط")], 0, "Paires mot / sens.", "Word / meaning pairs.", "أزواج كلمة / معنى."),
    Q("start=\"3\" sur ol :", "start=\"3\" on ol:", "start=\"3\" على ol:",
      [o("commence la numérotation à 3", "starts numbering at 3", "يبدأ الترقيم من 3"), o("crée 3 videos", "creates 3 videos", "ينشئ 3 فيديوهات"), o("est un iframe", "is an iframe", "iframe"), o("casse li", "breaks li", "يكسر li")], 0, "Attribut d’ol.", "ol attribute.", "سمة ol."),
    Q("type=\"A\" sur ol :", "type=\"A\" on ol:", "type=\"A\" على ol:",
      [o("A. B. C. au lieu de 1. 2. 3.", "A. B. C. instead of 1. 2. 3.", "A. B. C. بدل 1. 2. 3."), o("ajoute du son", "adds sound", "يضيف صوتًا"), o("est UTF-8", "is UTF-8", "UTF-8"), o("ouvre YouTube", "opens YouTube", "يفتح يوتيوب")], 0, "Lettres.", "Letters.", "حروف."),
    Q("Une liste n’est PAS :", "A list is NOT:", "القائمة ليست:",
      [o("un stockage de base de données", "database storage", "تخزين قاعدة بيانات"), o("une présentation", "a presentation", "عرضًا"), o("du HTML", "HTML", "HTML"), o("des li groupés", "grouped li", "li مجمّعة")], 0, "Juste de la mise en forme structurelle.", "Just structural formatting.", "مجرد تنسيق هيكلي."),
    Q("li peut contenir :", "li can contain:", "يمكن لـ li أن يحتوي:",
      [o("texte, liens, images, même un div", "text, links, images, even a div", "نصًا وروابط وصورًا وحتى div"), o("seulement un chiffre", "only a digit", "رقمًا فقط"), o("uniquement head", "only head", "head فقط"), o("un DOCTYPE", "a DOCTYPE", "DOCTYPE")], 0, "Conteneur d’item.", "Item container.", "حاوية عنصر."),
],
[
    P(("ul de 3 wilayas.", "ul of 3 wilayas.", "ul من 3 ولايات."), "", "<ul>\n<li>Alger</li>\n<li>Oran</li>\n<li>Constantine</li>\n</ul>", ("ul>li", "ul>li", "ul>li")),
    P(("ol de 3 étapes.", "ol of 3 steps.", "ol من 3 خطوات."), "", "<ol>\n<li>Contacter</li>\n<li>Voir</li>\n<li>Payer</li>\n</ol>", ("ol>li", "ol>li", "ol>li")),
    P(("dl HTML/CSS.", "dl HTML/CSS.", "dl HTML/CSS."), "", "<dl>\n<dt>HTML</dt>\n<dd>Structure la page.</dd>\n<dt>CSS</dt>\n<dd>Habille la page.</dd>\n</dl>", ("dt dd", "dt dd", "dt dd")),
    P(("Ajoute un 4e li.", "Add a 4th li.", "أضف li رابعًا."), "<ul><li>A</li><li>B</li><li>C</li></ul>", "<ul><li>A</li><li>B</li><li>C</li><li>D</li></ul>", ("un li de plus.", "one more li.", "li إضافي.")),
    P(("Transforme ul en ol.", "Turn ul into ol.", "حوّل ul إلى ol."), "<ul><li>Un</li><li>Deux</li></ul>", "<ol><li>Un</li><li>Deux</li></ol>", ("changer la balise parent.", "change the parent tag.", "غيّر الوسم الأب.")),
    P(("Liens dans ul.", "Links in ul.", "روابط داخل ul."), "", "<ul>\n<li><a href=\"https://www.google.com\">Google</a></li>\n<li><a href=\"https://www.facebook.com\">Facebook</a></li>\n</ul>", ("a dans li.", "a in li.", "a داخل li.")),
    P(("Images dans ol.", "Images in ol.", "صور داخل ol."), "", "<ol>\n<li><img src=\"images/image.png\" alt=\"1\" width=\"100\"></li>\n<li><img src=\"images/image2.png\" alt=\"2\" width=\"100\"></li>\n</ol>", ("img dans li.", "img in li.", "img داخل li.")),
    P(("Caractéristiques téléphone en ul.", "Phone specs in ul.", "مواصفات هاتف في ul."), "", "<ul>\n<li>128 Go</li>\n<li>Noir</li>\n<li>9/10</li>\n</ul>", ("puces produit.", "product bullets.", "نقاط المنتج.")),
    P(("Glossaire État 9/10.", "Glossary État 9/10.", "قاموس حالة 9/10."), "", "<dl>\n<dt>État 9/10</dt>\n<dd>Très bon état, micro-rayures possibles.</dd>\n</dl>", ("dt dd", "dt dd", "dt dd")),
    P(("Sous-liste : ul dans li.", "Sub-list: ul in li.", "قائمة فرعية: ul داخل li."), "<ul><li>Alger</li></ul>", "<ul>\n<li>Alger\n  <ul><li>Hydra</li><li>Centre</li></ul>\n</li>\n</ul>", ("imbriquer.", "nest.", "تداخل.")),
    P(("Corrige li hors ul.", "Fix li outside ul.", "صحّح li خارج ul."), "<li>Alger</li><li>Oran</li>", "<ul>\n<li>Alger</li>\n<li>Oran</li>\n</ul>", ("parent ul.", "parent ul.", "أب ul.")),
    P(("Corrige dt dans ul.", "Fix dt inside ul.", "صحّح dt داخل ul."), "<ul><dt>HTML</dt><dd>Langage</dd></ul>", "<dl><dt>HTML</dt><dd>Langage</dd></dl>", ("dl pas ul.", "dl not ul.", "dl لا ul.")),
    P(("ol start à 3.", "ol start at 3.", "ol يبدأ من 3."), "<ol><li>C</li><li>D</li></ol>", "<ol start=\"3\"><li>C</li><li>D</li></ol>", ("start", "start", "start")),
    P(("5 réseaux en ul.", "5 networks in ul.", "5 شبكات في ul."), "", "<ul>\n<li>Google</li>\n<li>Facebook</li>\n<li>Twitter</li>\n<li>Instagram</li>\n<li>Linkedin</li>\n</ul>", ("5 li.", "5 li.", "5 li.")),
    P(("Recette ol 4 étapes icône.", "Recipe ol 4 icon steps.", "وصفة ol من 4 خطوات أيقونة."), "", "<ol>\n<li>Flaticon</li>\n<li>Recherche</li>\n<li>Télécharger</li>\n<li>img src</li>\n</ol>", ("ordre.", "order.", "ترتيب.")),
    P(("dl trois termes web.", "dl three web terms.", "dl ثلاثة مصطلحات ويب."), "", "<dl>\n<dt>HTML</dt><dd>Structure</dd>\n<dt>CSS</dt><dd>Style</dd>\n<dt>JS</dt><dd>Interaction</dd>\n</dl>", ("3 paires.", "3 pairs.", "3 أزواج.")),
    P(("Mélange page : ul + ol.", "Mix page: ul + ol.", "صفحة مزيج: ul + ol."), "", "<h2>Avantages</h2>\n<ul><li>Boîte</li><li>Facture</li></ul>\n<h2>Étapes</h2>\n<ol><li>Appeler</li><li>Payer</li></ol>", ("deux listes.", "two lists.", "قائمتان.")),
    P(("li avec span de prix.", "li with price span.", "li مع span للسعر."), "<ul><li>iPhone 85000</li></ul>", "<ul><li>iPhone <span>85000 DA</span></li></ul>", ("span", "span", "span")),
    P(("Menu nav ul.", "Nav menu ul.", "قائمة nav ul."), "", "<nav>\n<ul>\n<li><a href=\"#\">Accueil</a></li>\n<li><a href=\"#\">Annonces</a></li>\n</ul>\n</nav>", ("nav>ul>li>a", "nav>ul>li>a", "nav>ul>li>a")),
    P(("Fiche complète listes.", "Full lists card.", "بطاقة قوائم كاملة."), "", "<h2>Galaxy A54</h2>\n<ul><li>128 Go</li><li>Noir</li></ul>\n<ol><li>Contacter</li><li>Voir</li><li>Payer</li></ol>\n<dl><dt>IMEI</dt><dd>Numéro unique du téléphone</dd></dl>", ("ul ol dl.", "ul ol dl.", "ul ol dl.")),
])

print("ch6 ok")
