# -*- coding: utf-8 -*-
from gen_exos import T, Q, P, o, make_ch

def bank(id_, file_, title, qs, ps):
    make_ch(id_, file_, title, qs, ps)

# ---- 3 ----
bank("chapitre-3", "chapitre-3.md", T("Chapitre 3 — Commentaires et éléments vides", "Chapter 3 — Comments and empty elements", "الفصل 3 — التعليقات والعناصر الفارغة"),
[
    Q("Un commentaire HTML commence par :", "An HTML comment starts with:", "يبدأ تعليق HTML بـ:",
      [o("/*", "/*", "/*"), o("<!--", "<!--", "<!--"), o("//", "//", "//"), o("#", "#", "#")], 1, "<!-- texte -->", "<!-- text -->", "<!-- نص -->"),
    Q("Le visiteur voit-il le commentaire ?", "Does the visitor see the comment?", "هل يرى الزائر التعليق؟",
      [o("Oui, en gros", "Yes, in bold", "نعم بخط غامق"), o("Non, il est invisible dans la page", "No, it is invisible on the page", "لا، غير ظاهر في الصفحة"), o("Seulement sur mobile", "Only on mobile", "على الجوال فقط"), o("Dans l’onglet", "In the tab", "في التبويب")], 1, "Le navigateur ignore le commentaire à l’affichage.", "The browser ignores it on screen.", "المتصفح يتجاهله في العرض."),
    Q("br sert à :", "br is for:", "br لـ:",
      [o("un trait horizontal", "a horizontal rule", "خط أفقي"), o("un saut de ligne", "a line break", "سطر جديد"), o("une image", "an image", "صورة"), o("un titre", "a heading", "عنوان")], 1, "br = line break.", "br = line break.", "br = كسر سطر."),
    Q("hr sert à :", "hr is for:", "hr لـ:",
      [o("une ligne horizontale", "a horizontal line", "خط أفقي"), o("un lien", "a link", "رابط"), o("un emoji", "an emoji", "إيموجي"), o("UTF-8", "UTF-8", "UTF-8")], 0, "Séparateur visuel.", "Visual separator.", "فاصل بصري."),
    Q("img est vide parce que :", "img is empty because:", "img فارغ لأن:",
      [o("il n’a pas de contenu texte entre deux balises ; le fichier est dans src", "it has no text content between tags; the file is in src", "لا محتوى نصي بين وسمين؛ الملف في src"), o("il est interdit", "it is forbidden", "ممنوع"), o("il va dans head seulement", "it only goes in head", "في head فقط"), o("il remplace html", "it replaces html", "يعوّض html")], 0, "Élément void.", "Void element.", "عنصر فارغ."),
    Q("On n’écrit PAS :", "We do NOT write:", "لا نكتب:",
      [o("</p>", "</p>", "</p>"), o("</img>", "</img>", "</img>"), o("</div>", "</div>", "</div>"), o("</a>", "</a>", "</a>")], 1, "Pas de balise fermante pour img.", "No closing tag for img.", "لا وسم إغلاق لـ img."),
    Q("Parmi ces éléments, lequel est vide ?", "Which of these is empty?", "أي هذه العناصر فارغ؟",
      [o("p", "p", "p"), o("div", "div", "div"), o("meta", "meta", "meta"), o("h1", "h1", "h1")], 2, "meta, br, hr, img, link, input, source.", "meta, br, hr, img, link, input, source.", "meta و br و hr و img و link و input و source."),
    Q("source (vidéo/audio) est :", "source (video/audio) is:", "source (فيديو/صوت) هو:",
      [o("un titre", "a heading", "عنوان"), o("un élément vide", "an empty element", "عنصر فارغ"), o("un commentaire", "a comment", "تعليق"), o("un iframe", "an iframe", "iframe")], 1, "Pas de </source>.", "No </source>.", "لا </source>."),
    Q("Plusieurs br d’affilée :", "Several br in a row:", "عدة br متتالية:",
      [o("est la meilleure façon de faire tout l’espacement d’un site", "is the best way to space a whole site", "أفضل طريقة لتباعد الموقع كله"), o("marche mais le CSS est préférable pour la mise en page", "works but CSS is better for layout", "تعمل لكن CSS أفضل للتخطيط"), o("créent un favicon", "create a favicon", "تنشئ أيقونة تبويب"), o("sont interdits par UTF-8", "are forbidden by UTF-8", "ممنوعة بسبب UTF-8")], 1, "br ≠ outil de layout.", "br is not a layout tool.", "br ليس أداة تخطيط."),
    Q("Un commentaire peut servir à :", "A comment can be used to:", "يمكن للتعليق أن:",
      [o("désactiver un bout de HTML sans l’effacer", "disable a piece of HTML without deleting it", "تعطيل جزء HTML دون حذفه"), o("lire un MP3", "play an MP3", "تشغيل MP3"), o("remplacer charset", "replace charset", "تعويض charset"), o("créer un ul", "create a ul", "إنشاء ul")], 0, "On commente le code pour le “éteindre”.", "Comment code out to turn it off.", "نعلّق الكود لإيقافه."),
    Q("link (favicon) est :", "link (favicon) is:", "link (أيقونة التبويب) هو:",
      [o("vide, dans head", "empty, in head", "فارغ في head"), o("un p", "a p", "p"), o("un h1", "an h1", "h1"), o("un audio", "an audio", "audio")], 0, "link est void.", "link is void.", "link فارغ."),
    Q("input de formulaire est :", "A form input is:", "حقل نموذج هو:",
      [o("vide", "empty", "فارغ"), o("un titre h2", "an h2 heading", "عنوان h2"), o("un article", "an article", "article"), o("un footer", "a footer", "footer")], 0, "Pas de </input>.", "No </input>.", "لا </input>."),
    Q("La bonne adresse d’un commentaire fermant :", "The correct comment closer is:", "إغلاق التعليق الصحيح هو:",
      [o("-->", "-->", "-->"), o("*/", "*/", "*/"), o("</comment>", "</comment>", "</comment>"), o("///", "///", "///")], 0, "<!-- ... -->", "<!-- ... -->", "<!-- ... -->"),
    Q("br vs p :", "br vs p:", "br مقابل p:",
      [o("p = paragraphe (bloc) ; br = aller à la ligne", "p = paragraph (block); br = line break", "p = فقرة (كتلة)؛ br = سطر جديد"), o("c’est la même chose", "they are the same", "نفس الشيء"), o("br va dans head", "br goes in head", "br في head"), o("p est vide", "p is empty", "p فارغ")], 0, "Rôles différents.", "Different jobs.", "مهمتان مختلفتان."),
    Q("On peut commenter :", "We can comment:", "يمكن التعليق على:",
      [o("une ligne ou un bloc de balises", "a line or a block of tags", "سطر أو كتلة وسوم"), o("seulement les images PNG", "only PNG images", "صور PNG فقط"), o("seulement les emojis", "only emojis", "الإيموجي فقط"), o("le DOCTYPE obligatoire", "the required DOCTYPE as only option", "DOCTYPE كخيار وحيد")], 0, "Très flexible.", "Very flexible.", "مرن جدًا."),
    Q("hr est :", "hr is:", "hr هو:",
      [o("un élément vide", "an empty element", "عنصر فارغ"), o("un lien", "a link", "رابط"), o("une liste", "a list", "قائمة"), o("un titre", "a heading", "عنوان")], 0, "void.", "void.", "فارغ."),
    Q("Quelle syntaxe est correcte ?", "Which syntax is correct?", "أي صيغة صحيحة؟",
      [o("<br></br>", "<br></br>", "<br></br>"), o("<br>", "<br>", "<br>"), o("</br>", "</br>", "</br>"), o("<break>", "<break>", "<break>")], 1, "<br> tout seul.", "<br> alone.", "<br> وحده."),
    Q("img a besoin de :", "img needs:", "img يحتاج:",
      [o("src (et alt recommandé)", "src (and alt recommended)", "src (و alt مستحسن)"), o("href seulement", "href only", "href فقط"), o("controls", "controls", "controls"), o("charset", "charset", "charset")], 0, "src = fichier.", "src = file.", "src = الملف."),
    Q("Un commentaire mal fermé peut :", "A badly closed comment can:", "تعليق غير مغلق جيدًا قد:",
      [o("cacher le HTML suivant", "hide the following HTML", "يخفي HTML التالي"), o("créer un MP4", "create an MP4", "ينشئ MP4"), o("traduire en arabe", "translate to Arabic", "يترجم للعربية"), o("ajouter un viewport", "add a viewport", "يضيف viewport")], 0, "Tout jusqu’au prochain --> disparaît.", "Everything until the next --> disappears.", "كل شيء حتى --> التالي يختفي."),
    Q("meta charset est un élément :", "meta charset is an element that is:", "meta charset عنصر:",
      [o("vide dans head", "empty in head", "فارغ في head"), o("un paragraphe", "a paragraph", "فقرة"), o("un footer", "a footer", "footer"), o("une ul", "a ul", "ul")], 0, "Configuration, pas de contenu.", "Configuration, no content.", "إعداد بلا محتوى."),
],
[
    P(("Ajoute un commentaire « menu ».", "Add a “menu” comment.", "أضف تعليق «menu»."), "<nav></nav>", "<!-- menu -->\n<nav></nav>", ("<!-- -->", "<!-- -->", "<!-- -->")),
    P(("Saut de ligne entre nom et ville.", "Line break between name and city.", "سطر جديد بين الاسم والمدينة."), "<p>Karim Alger</p>", "<p>Karim<br>Alger</p>", ("br", "br", "br")),
    P(("Trait sous le titre.", "A rule under the title.", "خط تحت العنوان."), "<h1>Contact</h1>\n<p>0550</p>", "<h1>Contact</h1>\n<hr>\n<p>0550</p>", ("hr", "hr", "hr")),
    P(("Image vide correcte avec alt.", "Correct empty image with alt.", "صورة فارغة صحيحة مع alt."), "", "<img src=\"photo.png\" alt=\"Annonce\">", ("pas de </img>", "no </img>", "بدون </img>")),
    P(("Commente le paragraphe (désactive-le).", "Comment out the paragraph.", "علّق الفقرة لتعطيلها."), "<p>Brouillon</p>", "<!-- <p>Brouillon</p> -->", ("entourer avec commentaire.", "wrap with comment.", "لف بتعليق.")),
    P(("Trois lignes d’adresse avec br.", "Three address lines with br.", "ثلاثة أسطر عنوان بـ br."), "<p>Karim Hydra 0550</p>", "<p>Karim<br>Hydra<br>0550</p>", ("deux br.", "two br.", "brان.")),
    P(("Corrige </br> en br correct.", "Fix </br> into a correct br.", "صحّح </br> إلى br صحيح."), "<p>A</br>B</p>", "<p>A<br>B</p>", ("<br>", "<br>", "<br>")),
    P(("Ajoute hr entre deux annonces.", "Add hr between two listings.", "أضف hr بين إعلانين."), "<h2>iPhone</h2>\n<h2>Galaxy</h2>", "<h2>iPhone</h2>\n<hr>\n<h2>Galaxy</h2>", ("hr", "hr", "hr")),
    P(("Commentaire de section PIED.", "FOOTER section comment.", "تعليق قسم التذييل."), "<footer>© 2026</footer>", "<!-- PIED DE PAGE -->\n<footer>© 2026</footer>", ("<!-- -->", "<!-- -->", "<!-- -->")),
    P(("meta charset vide dans un head.", "Empty meta charset in a head.", "meta charset فارغ في head."), "<head>\n<title>X</title>\n</head>", "<head>\n<meta charset=\"UTF-8\">\n<title>X</title>\n</head>", ("meta", "meta", "meta")),
    P(("Deux images l’une sous l’autre (br).", "Two images stacked (br).", "صورتان تحت بعض (br)."), "<img src=\"a.png\" alt=\"a\">\n<img src=\"b.png\" alt=\"b\">", "<img src=\"a.png\" alt=\"a\"><br>\n<img src=\"b.png\" alt=\"b\">", ("br entre les img.", "br between img.", "br بين img.")),
    P(("Commente l’image.", "Comment out the image.", "علّق الصورة."), "<img src=\"x.png\" alt=\"x\">", "<!-- <img src=\"x.png\" alt=\"x\"> -->", ("commentaire autour.", "comment around.", "تعليق حولها.")),
    P(("Adresse 4 lignes.", "4-line address.", "عنوان من 4 أسطر."), "<p>Nom Rue Ville Tel</p>", "<p>Nom<br>Rue<br>Ville<br>Tel</p>", ("br", "br", "br")),
    P(("hr + commentaire.", "hr + comment.", "hr + تعليق."), "<h1>A</h1>", "<h1>A</h1>\n<!-- séparateur -->\n<hr>", ("les deux.", "both.", "كلاهما.")),
    P(("Corrige </img>.", "Fix </img>.", "صحّح </img>."), "<img src=\"a.png\" alt=\"a\"></img>", "<img src=\"a.png\" alt=\"a\">", ("élément vide.", "empty element.", "عنصر فارغ.")),
    P(("link favicon (élément vide).", "favicon link (empty element).", "link الأيقونة (عنصر فارغ)."), "<head></head>", "<head>\n<link rel=\"shortcut icon\" href=\"icon.png\">\n</head>", ("link", "link", "link")),
    P(("source dans une video.", "source inside a video.", "source داخل video."), "<video controls></video>", "<video controls>\n<source src=\"v.mp4\" type=\"video/mp4\">\n</video>", ("source vide.", "empty source.", "source فارغ.")),
    P(("Double hr (deux séparateurs).", "Double hr (two separators).", "hr مزدوج."), "<p>A</p>\n<p>B</p>", "<p>A</p>\n<hr>\n<hr>\n<p>B</p>", ("deux hr.", "two hr.", "hrان.")),
    P(("Commentaire multiligne.", "Multiline comment.", "تعليق متعدد الأسطر."), "<div>carte</div>", "<!--\n  carte annonce\n-->\n<div>carte</div>", ("<!-- sur plusieurs lignes -->", "<!-- on several lines -->", "<!-- على عدة أسطر -->")),
    P(("Fiche contact complète.", "Full contact card.", "بطاقة اتصال كاملة."), "", "<h1>Contact</h1>\n<p>Karim<br>Hydra<br>0550</p>\n<hr>\n<p>Annonce 20481</p>", ("h1 p br hr.", "h1 p br hr.", "h1 p br hr.")),
])
print("ch3", "ok")
