# -*- coding: utf-8 -*-
from gen_exos import T, Q, P, o, make_ch as bank

def qs(*rows):
    return list(rows)

def ps(*rows):
    return list(rows)

bank("chapitre-4", "chapitre-4.md", T("Chapitre 4 — Titre et favicon", "Chapter 4 — Title and favicon", "الفصل 4 — العنوان والأيقونة"),
qs(
    Q("L’élément title se place dans :", "The title element goes in:", "عنصر title يوضع في:",
      [o("body", "body", "body"), o("head", "head", "head"), o("footer", "footer", "footer"), o("ul", "ul", "ul")], 1, "head = configuration.", "head = configuration.", "head = إعداد."),
    Q("title affiche le texte :", "title shows text:", "title يعرض النص:",
      [o("dans l’onglet", "in the tab", "في التبويب"), o("en h1 obligatoire", "as a required h1", "كـ h1 إلزامي"), o("en bas de page seulement", "only at the bottom", "أسفل الصفحة فقط"), o("dans une video", "in a video", "في فيديو")], 0, "Onglet + Google.", "Tab + Google.", "التبويب + جوجل."),
    Q("Le favicon est :", "The favicon is:", "أيقونة التبويب هي:",
      [o("la petite icône de l’onglet", "the small tab icon", "أيقونة التبويب الصغيرة"), o("une balise p", "a p tag", "وسم p"), o("un iframe", "an iframe", "iframe"), o("un audio", "an audio", "audio")], 0, "link rel=shortcut icon.", "link rel=shortcut icon.", "link rel=shortcut icon."),
    Q("L’attribut href du favicon contient :", "The favicon href contains:", "href للأيقونة يحتوي:",
      [o("le chemin du fichier image", "the image file path", "مسار ملف الصورة"), o("un paragraphe", "a paragraph", "فقرة"), o("un h1", "an h1", "h1"), o("target blank", "target blank", "target blank")], 0, "Chemin vers PNG/ICO.", "Path to PNG/ICO.", "مسار PNG/ICO."),
    Q("Flaticon sert ici à :", "Flaticon is used here to:", "Flaticon هنا لـ:",
      [o("télécharger une icône", "download an icon", "تنزيل أيقونة"), o("lire une video", "play a video", "تشغيل فيديو"), o("créer un ul", "create a ul", "إنشاء ul"), o("remplacer UTF-8", "replace UTF-8", "تعويض UTF-8")], 0, "Puis dossier icones/.", "Then icones/ folder.", "ثم مجلد icones/."),
    Q("h1 et title :", "h1 and title:", "h1 و title:",
      [o("sont exactement la même chose", "are exactly the same", "نفس الشيء تمامًا"), o("title = onglet, h1 = page", "title = tab, h1 = page", "title = التبويب، h1 = الصفحة"), o("h1 va dans head", "h1 goes in head", "h1 في head"), o("title va dans body", "title goes in body", "title في body")], 1, "Deux endroits différents.", "Two different places.", "مكانان مختلفان."),
    Q("rel=\"shortcut icon\" signifie :", "rel=\"shortcut icon\" means:", "rel=\"shortcut icon\" تعني:",
      [o("que ce link est l’icône du site", "that this link is the site icon", "أن هذا link هو أيقونة الموقع"), o("un lien Google", "a Google link", "رابط جوجل"), o("une video", "a video", "فيديو"), o("une liste", "a list", "قائمة")], 0, "rel décrit le rôle du link.", "rel describes the link’s role.", "rel يصف دور link."),
    Q("Sans title, l’onglet montre souvent :", "Without title, the tab often shows:", "بدون title يظهر التبويب غالبًا:",
      [o("Document / nom du fichier", "Document / file name", "Document / اسم الملف"), o("une video autoplay", "an autoplay video", "فيديو تلقائي"), o("un ul", "a ul", "ul"), o("un footer sémantique", "a semantic footer", "footer دلالي")], 0, "D’où l’intérêt de title.", "Hence title matters.", "لذلك title مهم."),
    Q("type=\"image/png\" :", "type=\"image/png\":", "type=\"image/png\":",
      [o("indique le type MIME du fichier icône", "gives the icon file MIME type", "يوضح نوع MIME لملف الأيقونة"), o("crée un paragraphe", "creates a paragraph", "ينشئ فقرة"), o("est un h6", "is an h6", "h6"), o("remplace src d’une video", "replaces a video src", "يعوّض src لفيديو")], 0, "type du link.", "link type.", "نوع link."),
    Q("On met le favicon :", "We put the favicon:", "نضع الأيقونة:",
      [o("dans head", "in head", "في head"), o("après </html>", "after </html>", "بعد </html>"), o("dans un li seulement", "in an li only", "في li فقط"), o("dans audio", "in audio", "في audio")], 0, "Toujours head.", "Always head.", "دائمًا head."),
    Q("VS Code snippet link:favicon donne :", "VS Code snippet link:favicon gives:", "اختصار VS Code link:favicon يعطي:",
      [o("une ligne link rel=shortcut icon", "a link rel=shortcut icon line", "سطر link rel=shortcut icon"), o("un iframe YouTube", "a YouTube iframe", "iframe يوتيوب"), o("une ol", "an ol", "ol"), o("un mark", "a mark", "mark")], 0, "Puis on remplit href.", "Then fill href.", "ثم نملأ href."),
    Q("Un bon title d’annonce :", "A good listing title:", "عنوان تبويب جيد لإعلان:",
      [o("Peugeot 208 Alger | Aboni", "Peugeot 208 Alger | Aboni", "Peugeot 208 Alger | Aboni"), o("", "", ""), o("<script>", "<script>", "<script>"), o("aaaa", "aaaa", "aaaa")], 0, "Clair et unique.", "Clear and unique.", "واضح وفريد."),
    Q("Le fichier icône se range souvent dans :", "The icon file is often stored in:", "ملف الأيقونة يُحفظ غالبًا في:",
      [o("icones/", "icones/", "icones/"), o("head/body/head", "head/body/head", "head/body/head"), o("un commentaire", "a comment", "تعليق"), o("un dl", "a dl", "dl")], 0, "Dossier d’images.", "Image folder.", "مجلد صور."),
    Q("link est un élément :", "link is an element that is:", "link عنصر:",
      [o("vide", "empty", "فارغ"), o("avec </link> obligatoire", "with required </link>", "مع </link> إلزامي"), o("un titre", "a heading", "عنوان"), o("un span", "a span", "span")], 0, "Void.", "Void.", "فارغ."),
    Q("On peut avoir title ET h1 différents :", "title AND h1 can differ:", "يمكن أن يختلف title و h1:",
      [o("Oui", "Yes", "نعم"), o("Non, interdit", "No, forbidden", "لا، ممنوع"), o("Seulement en arabe", "Only in Arabic", "بالعربية فقط"), o("Seulement sans charset", "Only without charset", "بدون charset فقط")], 0, "Souvent le title est plus long (SEO).", "title is often longer (SEO).", "title أطول غالبًا (SEO)."),
    Q("href vide dans le favicon :", "Empty href in the favicon:", "href فارغ في الأيقونة:",
      [o("n’affiche pas l’icône", "does not show the icon", "لا يظهر الأيقونة"), o("crée une video", "creates a video", "ينشئ فيديو"), o("est le meilleur cas", "is the best case", "أفضل حالة"), o("remplace UTF-8", "replaces UTF-8", "يعوّض UTF-8")], 0, "Il faut le chemin du fichier.", "You need the file path.", "تحتاج مسار الملف."),
    Q("L’icône PNG 32×32 :", "A 32×32 PNG icon:", "أيقونة PNG 32×32:",
      [o("convient bien à un favicon simple", "suits a simple favicon", "مناسبة لأيقونة تبويب بسيطة"), o("doit être une video mp4", "must be an mp4 video", "يجب أن تكون فيديو mp4"), o("va dans ol seulement", "goes in ol only", "في ol فقط"), o("casse br", "breaks br", "تكسر br")], 0, "Petit fichier.", "Small file.", "ملف صغير."),
    Q("title trop long :", "A title that is too long:", "title طويل جدًا:",
      [o("sera coupé dans l’onglet", "will be cut in the tab", "يُقص في التبويب"), o("crée 10 h1", "creates 10 h1", "ينشئ 10 h1"), o("est obligatoire", "is required", "إلزامي"), o("remplace nav", "replaces nav", "يعوّض nav")], 0, "Reste concis.", "Keep it short.", "اختصر."),
    Q("On télécharge l’icône PUIS :", "We download the icon THEN:", "نزّل الأيقونة ثم:",
      [o("on écrit le chemin dans href", "we write the path in href", "نكتب المسار في href"), o("on supprime head", "we delete head", "نحذف head"), o("on ajoute </img> au link", "we add </img> to link", "نضيف </img> لـ link"), o("on met title dans body", "we put title in body", "نضع title في body")], 0, "Fichier d’abord, chemin ensuite.", "File first, path next.", "الملف أولًا ثم المسار."),
    Q("Le couple visible de l’onglet :", "The visible tab pair is:", "الثنائي الظاهر في التبويب:",
      [o("favicon + title", "favicon + title", "الأيقونة + title"), o("ul + ol", "ul + ol", "ul + ol"), o("video + audio", "video + audio", "video + audio"), o("iframe + source", "iframe + source", "iframe + source")], 0, "Les deux se voient dans l’onglet.", "Both are seen in the tab.", "كلاهما يظهر في التبويب."),
),
ps(
    P(("Ajoute un title « Annonces Alger ».", "Add title “Annonces Alger”.", "أضف title «Annonces Alger»."), "<head></head>", "<head>\n  <title>Annonces Alger</title>\n</head>", ("title dans head.", "title in head.", "title في head.")),
    P(("Ajoute un favicon PNG.", "Add a PNG favicon.", "أضف أيقونة PNG."), "<head>\n<title>X</title>\n</head>", "<head>\n<title>X</title>\n<link rel=\"shortcut icon\" href=\"icones/html.png\" type=\"image/png\">\n</head>", ("link", "link", "link")),
    P(("Change le title pour Peugeot 208.", "Change the title to Peugeot 208.", "غيّر title إلى Peugeot 208."), "<title>Document</title>", "<title>Peugeot 208 | Alger</title>", ("texte entre les balises.", "text between tags.", "النص بين الوسمين.")),
    P(("href vers icones/logo.png.", "href to icones/logo.png.", "href نحو icones/logo.png."), "<link rel=\"shortcut icon\" href=\"\" type=\"image/png\">", "<link rel=\"shortcut icon\" href=\"icones/logo.png\" type=\"image/png\">", ("remplir href.", "fill href.", "املأ href.")),
    P(("title + h1 différents.", "Different title and h1.", "title و h1 مختلفان."), "<head></head>\n<body></body>", "<head><title>Ouedkniss Alger</title></head>\n<body><h1>Annonces</h1></body>", ("onglet ≠ page.", "tab ≠ page.", "التبويب ≠ الصفحة.")),
    P(("type image/x-icon.", "type image/x-icon.", "type image/x-icon."), "<link rel=\"shortcut icon\" href=\"f.ico\">", "<link rel=\"shortcut icon\" href=\"f.ico\" type=\"image/x-icon\">", ("type", "type", "type")),
    P(("Deux lignes : charset et title.", "Two lines: charset and title.", "سطران: charset و title."), "<head></head>", "<head>\n<meta charset=\"UTF-8\">\n<title>Aboni</title>\n</head>", ("meta puis title.", "meta then title.", "meta ثم title.")),
    P(("Favicon + title mini site.", "Favicon + title mini site.", "أيقونة + title لموقع مصغر."), "<head></head>", "<head>\n<title>Mini Ouedkniss</title>\n<link rel=\"shortcut icon\" href=\"icones/html.png\">\n</head>", ("les deux.", "both.", "كلاهما.")),
    P(("Corrige title mis dans body.", "Fix title placed in body.", "صحّح title الموضوع في body."), "<body><title>X</title><h1>X</h1></body>", "<head><title>X</title></head>\n<body><h1>X</h1></body>", ("title → head.", "title → head.", "title → head.")),
    P(("Title SEO : produit + ville.", "SEO title: product + city.", "title لمحرك البحث: منتج + مدينة."), "<title>Document</title>", "<title>iPhone 13 Alger | Aboni</title>", ("mots clés.", "keywords.", "كلمات مفتاحية.")),
    P(("rel shortcut icon manquant.", "Missing rel shortcut icon.", "rel shortcut icon ناقص."), "<link href=\"i.png\">", "<link rel=\"shortcut icon\" href=\"i.png\">", ("rel", "rel", "rel")),
    P(("Chemin relatif icones/html-5.png.", "Relative path icones/html-5.png.", "مسار نسبي icones/html-5.png."), "<link rel=\"shortcut icon\" href=\"html-5.png\">", "<link rel=\"shortcut icon\" href=\"icones/html-5.png\">", ("dossier icones.", "icones folder.", "مجلد icones.")),
    P(("Ajoute lang=fr sur html et un title.", "Add lang=fr on html and a title.", "أضف lang=fr على html و title."), "<html>\n<head></head>\n</html>", "<html lang=\"fr\">\n<head><title>Cours HTML</title></head>\n</html>", ("lang + title.", "lang + title.", "lang + title.")),
    P(("title avec emoji (UTF-8 déjà là).", "title with emoji (UTF-8 already there).", "title مع إيموجي (UTF-8 موجود)."), "<title>Annonces</title>", "<title>Annonces 🇩🇿</title>", ("coller l’emoji.", "paste the emoji.", "الصق الإيموجي.")),
    P(("Commentaire puis favicon.", "Comment then favicon.", "تعليق ثم أيقونة."), "<head></head>", "<head>\n<!-- icone onglet -->\n<link rel=\"shortcut icon\" href=\"icones/html.png\">\n</head>", ("commentaire.", "comment.", "تعليق.")),
    P(("Remplace Document.", "Replace Document.", "استبدل Document."), "<title>Document</title>", "<title>Chapitre 4 | Aboni</title>", ("nouveau texte.", "new text.", "نص جديد.")),
    P(("Favicon type png et href.", "Favicon type png and href.", "أيقونة type png و href."), "<link rel=\"shortcut icon\">", "<link rel=\"shortcut icon\" href=\"icones/html.png\" type=\"image/png\">", ("href + type.", "href + type.", "href + type.")),
    P(("Head complet chapitre 4.", "Full chapter 4 head.", "head كامل للفصل 4."), "<head></head>", "<head>\n<meta charset=\"UTF-8\">\n<title>Séance HTML</title>\n<link rel=\"shortcut icon\" href=\"icones/html.png\" type=\"image/png\">\n</head>", ("3 lignes.", "3 lines.", "3 أسطر.")),
    P(("Ne pas mettre le favicon en img dans body : utilise link.", "Do not use img in body for favicon: use link.", "لا تستخدم img في body للأيقونة: استخدم link."), "<body><img src=\"icones/html.png\" alt=\"icon\"></body>", "<head>\n<link rel=\"shortcut icon\" href=\"icones/html.png\">\n</head>\n<body></body>", ("link head.", "link head.", "link في head.")),
    P(("Title h1 cohérents mais pas identiques.", "Consistent but not identical title/h1.", "title و h1 متناسقان لا متطابقان."), "", "<head><title>Ouedkniss — Téléphones Alger</title></head>\n<body><h1>Téléphones à Alger</h1></body>", ("complémentaires.", "complementary.", "متكاملان.")),
))
print("ch4 ok")
