# -*- coding: utf-8 -*-
from gen_exos import T, Q, P, o, make_ch

make_ch("chapitre-9", "chapitre-9.md", T("Chapitre 9 — Vidéo", "Chapter 9 — Video", "الفصل 9 — الفيديو"),
[
    Q("L’élément pour un fichier vidéo local est :", "The element for a local video file is:", "عنصر ملف فيديو محلي هو:",
      [o("video", "video", "video"), o("audio", "audio", "audio"), o("ol", "ol", "ol"), o("title", "title", "title")], 0, "Pas YouTube : YouTube = iframe.", "Not YouTube: YouTube = iframe.", "ليس يوتيوب: يوتيوب = iframe."),
    Q("Sans controls :", "Without controls:", "بدون controls:",
      [o("pas de boutons play/pause", "no play/pause buttons", "لا أزرار تشغيل/إيقاف"), o("la video devient une liste", "the video becomes a list", "يصبح الفيديو قائمة"), o("UTF-8 se casse", "UTF-8 breaks", "UTF-8 ينكسر"), o("on a un favicon", "we get a favicon", "نحصل على أيقونة تبويب")], 0, "Toujours controls en cours.", "Always controls in class.", "controls دائمًا في الدرس."),
    Q("source sert à :", "source is for:", "source لـ:",
      [o("plusieurs formats ; le navigateur saute si non supporté", "several formats; the browser skips if unsupported", "عدة صيغ؛ المتصفح يتخطى إن لم تُدعم"), o("créer un h1", "create an h1", "إنشاء h1"), o("un commentaire", "a comment", "تعليق"), o("un dl", "a dl", "dl")], 0, "mp4, webm, ogg.", "mp4, webm, ogg.", "mp4 و webm و ogg."),
    Q("type d’un MP4 :", "type of an MP4:", "type لـ MP4:",
      [o("video/mp4", "video/mp4", "video/mp4"), o("audio/mpeg", "audio/mpeg", "audio/mpeg"), o("text/css", "text/css", "text/css"), o("image/png", "image/png", "image/png")], 0, "Attribut type de source.", "source type attribute.", "سمة type لـ source."),
    Q("Le format le plus sûr aujourd’hui :", "The safest format today:", "الصيغة الأكثر أمانًا اليوم:",
      [o("MP4", "MP4", "MP4"), o("un fichier Word", "a Word file", "ملف وورد"), o("un ol", "an ol", "ol"), o("un favicon", "a favicon", "أيقونة تبويب")], 0, "Très compatible.", "Very compatible.", "متوافق جدًا."),
    Q("poster :", "poster:", "poster:",
      [o("image avant la lecture", "image before playback", "صورة قبل التشغيل"), o("un type audio", "an audio type", "نوع صوت"), o("un ul", "a ul", "ul"), o("un charset", "a charset", "charset")], 0, "Miniature.", "Thumbnail.", "صورة مصغرة."),
    Q("muted + autoplay :", "muted + autoplay:", "muted + autoplay:",
      [o("souvent autorisé (autoplay seul est bloqué)", "often allowed (autoplay alone is blocked)", "مسموح غالبًا (autoplay وحده يُحظر)"), o("interdit en HTML", "forbidden in HTML", "ممنوع في HTML"), o("crée un footer", "creates a footer", "ينشئ footer"), o("est un li", "is an li", "li")], 0, "Politique des navigateurs.", "Browser policy.", "سياسة المتصفحات."),
    Q("loop :", "loop:", "loop:",
      [o("recommence en boucle", "repeats in a loop", "يعيد في حلقة"), o("ouvre un onglet", "opens a tab", "يفتح تبويبًا"), o("est un dt", "is a dt", "dt"), o("remplace src", "replaces src", "يعوّض src")], 0, "Boucle.", "Loop.", "حلقة."),
    Q("Le texte dans video s’affiche si :", "Text inside video shows if:", "النص داخل video يظهر إذا:",
      [o("aucun format n’est lu", "no format can be played", "لا صيغة تُشغَّل"), o("on a un h1", "we have an h1", "لدينا h1"), o("on a UTF-8 seulement", "we have UTF-8 only", "لدينا UTF-8 فقط"), o("on a un nav", "we have a nav", "لدينا nav")], 0, "Fallback.", "Fallback.", "احتياطي."),
    Q("width / height :", "width / height:", "width / height:",
      [o("taille du lecteur", "player size", "حجم المشغّل"), o("couleur", "color", "لون"), o("une liste", "a list", "قائمة"), o("un emoji", "an emoji", "إيموجي")], 0, "Comme une image.", "Like an image.", "مثل صورة."),
    Q("YouTube s’intègre avec :", "YouTube is embedded with:", "يُدمج يوتيوب بـ:",
      [o("iframe, pas video", "iframe, not video", "iframe وليس video"), o("ul", "ul", "ul"), o("mark", "mark", "mark"), o("sub", "sub", "sub")], 0, "Chapitre 11.", "Chapter 11.", "الفصل 11."),
    Q("source est un élément :", "source is an element that is:", "source عنصر:",
      [o("vide", "empty", "فارغ"), o("un titre", "a heading", "عنوان"), o("un main", "a main", "main"), o("un article", "an article", "article")], 0, "Pas de </source>.", "No </source>.", "لا </source>."),
    Q("preload :", "preload:", "preload:",
      [o("auto / metadata / none", "auto / metadata / none", "auto / metadata / none"), o("ul / ol / dl", "ul / ol / dl", "ul / ol / dl"), o("b / i / u", "b / i / u", "b / i / u"), o("header / footer", "header / footer", "header / footer")], 0, "Chargement.", "Loading.", "تحميل."),
    Q("On met autant de source que :", "We put as many source as:", "نضع من source بقدر:",
      [o("de formats disponibles", "available formats", "الصيغ المتوفرة"), o("de h1", "of h1", "h1"), o("de wilayas", "of wilayas", "الولايات"), o("de favicons", "of favicons", "أيقونات التبويب")], 0, "Le navigateur choisit.", "The browser chooses.", "المتصفح يختار."),
    Q("src sur video (cas simple) :", "src on video (simple case):", "src على video (حالة بسيطة):",
      [o("chemin du fichier", "file path", "مسار الملف"), o("un dt", "a dt", "dt"), o("un target", "a target", "target"), o("un rel", "a rel", "rel")], 0, "videos/video.mp4", "videos/video.mp4", "videos/video.mp4"),
    Q("webm type :", "webm type:", "نوع webm:",
      [o("video/webm", "video/webm", "video/webm"), o("audio/wav", "audio/wav", "audio/wav"), o("text/html", "text/html", "text/html"), o("image/x-icon", "image/x-icon", "image/x-icon")], 0, "Deuxième format courant.", "Second common format.", "صيغة ثانية شائعة."),
    Q("ogg vidéo type :", "ogg video type:", "نوع فيديو ogg:",
      [o("video/ogg", "video/ogg", "video/ogg"), o("audio/mpeg", "audio/mpeg", "audio/mpeg"), o("application/pdf", "application/pdf", "application/pdf"), o("font/ttf", "font/ttf", "font/ttf")], 0, "Troisième format.", "Third format.", "صيغة ثالثة."),
    Q("video contient source, pas l’inverse :", "video contains source, not the reverse:", "video يحتوي source لا العكس:",
      [o("Vrai", "True", "صحيح"), o("Faux, source contient video", "False, source contains video", "خطأ، source يحتوي video"), o("Faux, c’est ol", "False, it is ol", "خطأ، إنه ol"), o("Faux, c’est head", "False, it is head", "خطأ، إنه head")], 0, "Parent video.", "Parent video.", "الأب video."),
    Q("Un fichier .docx dans video :", "A .docx file in video:", "ملف .docx في video:",
      [o("ne se lira pas comme une video", "will not play as video", "لن يُشغَّل كفيديو"), o("devient un h1", "becomes an h1", "يصبح h1"), o("est recommandé", "is recommended", "مستحسن"), o("remplace charset", "replaces charset", "يعوّض charset")], 0, "Mauvais type.", "Wrong type.", "نوع خاطئ."),
    Q("controls est un attribut :", "controls is an attribute:", "controls سمة:",
      [o("booléen (présent = afficher la barre)", "boolean (present = show the bar)", "منطقية (وجودها = إظهار الشريط)"), o("qui vaut toujours mp4", "that always equals mp4", "قيمتها mp4 دائمًا"), o("de ol", "of ol", "لـ ol"), o("de title onglet", "of the tab title", "لعنوان التبويب")], 0, "Pas besoin de =\"true\".", "No need for =\"true\".", "لا حاجة لـ =\"true\"."),
],
[
    P(("video simple + controls.", "simple video + controls.", "video بسيط + controls."), "", "<video src=\"videos/video.mp4\" controls></video>", ("src + controls", "src + controls", "src + controls")),
    P(("Ajoute controls.", "Add controls.", "أضف controls."), "<video src=\"videos/video.mp4\"></video>", "<video src=\"videos/video.mp4\" controls></video>", ("controls", "controls", "controls")),
    P(("width 640 height 360.", "width 640 height 360.", "width 640 height 360."), "<video src=\"videos/video.mp4\" controls></video>", "<video src=\"videos/video.mp4\" controls width=\"640\" height=\"360\"></video>", ("taille", "size", "حجم")),
    P(("3 source mp4 webm ogg.", "3 source mp4 webm ogg.", "3 source mp4 webm ogg."), "<video controls></video>", "<video controls>\n<source src=\"videos/video.mp4\" type=\"video/mp4\">\n<source src=\"videos/video.webm\" type=\"video/webm\">\n<source src=\"videos/video.ogg\" type=\"video/ogg\">\n</video>", ("formats", "formats", "صيغ")),
    P(("Texte fallback.", "Fallback text.", "نص احتياطي."), "<video src=\"videos/video.mp4\" controls></video>", "<video src=\"videos/video.mp4\" controls>Ton navigateur ne lit pas la vidéo.</video>", ("texte intérieur.", "inner text.", "نص داخلي.")),
    P(("muted loop.", "muted loop.", "muted loop."), "<video src=\"videos/video.mp4\" controls></video>", "<video src=\"videos/video.mp4\" controls muted loop></video>", ("deux attributs.", "two attributes.", "سمتان.")),
    P(("poster.", "poster.", "poster."), "<video src=\"videos/video.mp4\" controls></video>", "<video src=\"videos/video.mp4\" controls poster=\"images/apercu.jpg\"></video>", ("poster", "poster", "poster")),
    P(("type manquant sur source.", "missing type on source.", "type ناقص على source."), "<source src=\"videos/video.mp4\">", "<source src=\"videos/video.mp4\" type=\"video/mp4\">", ("type", "type", "type")),
    P(("Corrige audio pour une video.", "Fix audio used for a video.", "صحّح audio المستخدم لفيديو."), "<audio src=\"videos/video.mp4\" controls></audio>", "<video src=\"videos/video.mp4\" controls></video>", ("video", "video", "video")),
    P(("Chemin videos/video.mp4.", "Path videos/video.mp4.", "مسار videos/video.mp4."), "<video controls></video>", "<video src=\"videos/video.mp4\" controls></video>", ("src", "src", "src")),
    P(("h2 + video visite.", "h2 + visit video.", "h2 + فيديو زيارة."), "", "<h2>Visite virtuelle — F3 Hydra</h2>\n<video src=\"videos/video.mp4\" controls width=\"640\"></video>", ("exemple réel.", "real example.", "مثال حقيقي.")),
    P(("preload none.", "preload none.", "preload none."), "<video src=\"v.mp4\" controls></video>", "<video src=\"v.mp4\" controls preload=\"none\"></video>", ("preload", "preload", "preload")),
    P(("Deuxieme source webm.", "Second webm source.", "source webm ثانٍ."), "<video controls>\n<source src=\"v.mp4\" type=\"video/mp4\">\n</video>", "<video controls>\n<source src=\"v.mp4\" type=\"video/mp4\">\n<source src=\"v.webm\" type=\"video/webm\">\n</video>", ("ajouter source.", "add source.", "أضف source.")),
    P(("autoplay muted.", "autoplay muted.", "autoplay muted."), "<video src=\"v.mp4\" controls></video>", "<video src=\"v.mp4\" controls autoplay muted></video>", ("les deux.", "both.", "كلاهما.")),
    P(("Ne pas utiliser iframe pour un mp4 local.", "Do not use iframe for a local mp4.", "لا تستخدم iframe لـ mp4 محلي."), "<iframe src=\"videos/video.mp4\"></iframe>", "<video src=\"videos/video.mp4\" controls></video>", ("video", "video", "video")),
    P(("height 280.", "height 280.", "height 280."), "<video src=\"v.mp4\" controls width=\"500\"></video>", "<video src=\"v.mp4\" controls width=\"500\" height=\"280\"></video>", ("height", "height", "height")),
    P(("source ogg.", "ogg source.", "source ogg."), "<video controls></video>", "<video controls>\n<source src=\"videos/video.ogg\" type=\"video/ogg\">\n</video>", ("video/ogg", "video/ogg", "video/ogg")),
    P(("Article + video.", "Article + video.", "article + video."), "", "<article>\n<h3>Visite F3</h3>\n<video src=\"videos/video.mp4\" controls></video>\n</article>", ("conteneur + média.", "container + media.", "حاوية + وسائط.")),
    P(("Corrige type audio/mpeg sur mp4.", "Fix audio/mpeg type on mp4.", "صحّح type audio/mpeg على mp4."), "<source src=\"v.mp4\" type=\"audio/mpeg\">", "<source src=\"v.mp4\" type=\"video/mp4\">", ("video/mp4", "video/mp4", "video/mp4")),
    P(("Lecteur complet 3 formats + fallback.", "Full player 3 formats + fallback.", "مشغّل كامل 3 صيغ + احتياطي."), "", "<video controls width=\"500\">\n<source src=\"videos/video.mp4\" type=\"video/mp4\">\n<source src=\"videos/video.webm\" type=\"video/webm\">\n<source src=\"videos/video.ogg\" type=\"video/ogg\">\nNavigateur non supporté.\n</video>", ("notes du chapitre 9.", "chapter 9 notes.", "ملاحظات الفصل 9.")),
])

make_ch("chapitre-10", "chapitre-10.md", T("Chapitre 10 — Audio", "Chapter 10 — Audio", "الفصل 10 — الصوت"),
[
    Q("Même logique que video mais :", "Same logic as video but:", "نفس منطق video لكن:",
      [o("sans image", "without a picture", "بلا صورة"), o("sans controls jamais", "never with controls", "بدون controls أبدًا"), o("uniquement dans head", "only in head", "في head فقط"), o("remplace html", "replaces html", "يعوّض html")], 0, "audio = son.", "audio = sound.", "audio = صوت."),
    Q("Fichier simple :", "Simple file:", "ملف بسيط:",
      [o("<audio src=\"audio/audio.mp3\" controls>", "<audio src=\"audio/audio.mp3\" controls>", "<audio src=\"audio/audio.mp3\" controls>"), o("<ul src=\"audio.mp3\">", "<ul src=\"audio.mp3\">", "<ul src=\"audio.mp3\">"), o("<p controls>", "<p controls>", "<p controls>"), o("<img src=\"audio.mp3\">", "<img src=\"audio.mp3\">", "<img src=\"audio.mp3\">")], 0, "src + controls.", "src + controls.", "src + controls."),
    Q("type MP3 :", "MP3 type:", "نوع MP3:",
      [o("audio/mpeg", "audio/mpeg", "audio/mpeg"), o("video/mp4", "video/mp4", "video/mp4"), o("text/css", "text/css", "text/css"), o("image/png", "image/png", "image/png")], 0, "Parfois écrit audio/mp3.", "Sometimes written audio/mp3.", "يُكتب أحيانًا audio/mp3."),
    Q("ogg audio :", "ogg audio:", "ogg للصوت:",
      [o("audio/ogg", "audio/ogg", "audio/ogg"), o("video/ogg seulement", "video/ogg only", "video/ogg فقط"), o("text/html", "text/html", "text/html"), o("rel icon", "rel icon", "rel icon")], 0, "Deuxième format.", "Second format.", "صيغة ثانية."),
    Q("wav :", "wav:", "wav:",
      [o("audio/wav", "audio/wav", "audio/wav"), o("video/mp4", "video/mp4", "video/mp4"), o("application/json", "application/json", "application/json"), o("font/woff", "font/woff", "font/woff")], 0, "Troisième format.", "Third format.", "صيغة ثالثة."),
    Q("Si un format n’est pas supporté :", "If a format is unsupported:", "إذا لم تُدعم صيغة:",
      [o("le navigateur saute au source suivant", "the browser jumps to the next source", "المتصفح ينتقل إلى source التالي"), o("la page explose", "the page explodes", "الصفحة تنفجر"), o("UTF-8 s’enlève", "UTF-8 is removed", "يُحذف UTF-8"), o("ol se crée", "ol is created", "يُنشأ ol")], 0, "Comme la video.", "Like video.", "مثل الفيديو."),
    Q("width/height sur audio :", "width/height on audio:", "width/height على audio:",
      [o("ne s’appliquent pas vraiment (pas une image)", "do not really apply (not an image)", "لا تنطبق فعليًا (ليست صورة)"), o("sont obligatoires", "are required", "إلزاميان"), o("créent un iframe", "create an iframe", "ينشئان iframe"), o("remplacent controls", "replace controls", "يعوّضان controls")], 0, "Barre par défaut.", "Default bar.", "شريط افتراضي."),
    Q("controls sur audio :", "controls on audio:", "controls على audio:",
      [o("play / pause / volume / barre", "play / pause / volume / bar", "تشغيل / إيقاف / صوت / شريط"), o("un h1", "an h1", "h1"), o("un favicon", "a favicon", "أيقونة تبويب"), o("un dl", "a dl", "dl")], 0, "Toujours les mettre.", "Always add them.", "ضعها دائمًا."),
    Q("loop sur audio :", "loop on audio:", "loop على audio:",
      [o("rejoue en boucle", "replays in a loop", "يعيد التشغيل في حلقة"), o("ouvre Google", "opens Google", "يفتح جوجل"), o("est un span", "is a span", "span"), o("est un header", "is a header", "header")], 0, "Musique de fond (avec prudence).", "Background music (carefully).", "موسيقى خلفية (بحذر)."),
    Q("autoplay audio :", "autoplay audio:", "autoplay للصوت:",
      [o("souvent bloqué sans interaction", "often blocked without interaction", "يُحظر غالبًا بلا تفاعل"), o("toujours autorisé", "always allowed", "مسموح دائمًا"), o("crée un ul", "creates a ul", "ينشئ ul"), o("est charset", "is charset", "charset")], 0, "Les navigateurs protègent l’utilisateur.", "Browsers protect the user.", "المتصفحات تحمي المستخدم."),
    Q("video vs audio : poster :", "video vs audio: poster:", "video مقابل audio: poster:",
      [o("poster existe pour video, pas pour audio", "poster exists for video, not audio", "poster موجود للفيديو لا للصوت"), o("audio a toujours poster", "audio always has poster", "audio لديه poster دائمًا"), o("poster est un ol", "poster is an ol", "poster هو ol"), o("poster est UTF-8", "poster is UTF-8", "poster هو UTF-8")], 0, "Pas d’image d’audio.", "No audio image.", "لا صورة للصوت."),
    Q("source va dans :", "source goes in:", "source يوضع في:",
      [o("audio (ou video)", "audio (or video)", "audio (أو video)"), o("title onglet", "tab title", "عنوان التبويب"), o("uniquement nav", "nav only", "nav فقط"), o("DOCTYPE", "DOCTYPE", "DOCTYPE")], 0, "Parent média.", "Media parent.", "أب الوسائط."),
    Q("Le plus compatible audio :", "Most compatible audio:", "الصوت الأكثر توافقًا:",
      [o("MP3", "MP3", "MP3"), o("un fichier EXE", "an EXE file", "ملف EXE"), o("un h6", "an h6", "h6"), o("un iframe maps", "a maps iframe", "iframe خرائط")], 0, "audio/mpeg.", "audio/mpeg.", "audio/mpeg."),
    Q("Chemin du cours :", "Course path:", "مسار الدرس:",
      [o("audio/audio.mp3", "audio/audio.mp3", "audio/audio.mp3"), o("videos/video.mp4 seulement", "videos/video.mp4 only", "videos/video.mp4 فقط"), o("icones/html.png comme son", "icones/html.png as sound", "icones/html.png كصوت"), o("chapitre-1/index.html comme mp3", "chapitre-1/index.html as mp3", "chapitre-1/index.html كـ mp3")], 0, "Corriger audios/ vs audio/.", "Fix audios/ vs audio/.", "صحّح audios/ مقابل audio/."),
    Q("Fallback texte :", "Fallback text:", "النص الاحتياطي:",
      [o("entre <audio> et </audio>", "between <audio> and </audio>", "بين <audio> و </audio>"), o("dans head seulement", "in head only", "في head فقط"), o("dans charset", "in charset", "في charset"), o("dans rel", "in rel", "في rel")], 0, "Si rien n’est lu.", "If nothing plays.", "إن لم يُشغَّل شيء."),
    Q("preload metadata :", "preload metadata:", "preload metadata:",
      [o("charge les infos, pas tout le fichier", "loads info, not the whole file", "يحمّل المعلومات لا الملف كله"), o("crée 10 ol", "creates 10 ol", "ينشئ 10 ol"), o("est un emoji", "is an emoji", "إيموجي"), o("est un footer", "is a footer", "footer")], 0, "Compromis.", "A compromise.", "حل وسط."),
    Q("On n’utilise pas audio pour YouTube.", "We do not use audio for YouTube.", "لا نستخدم audio ليوتيوب.",
      [o("Vrai (iframe)", "True (iframe)", "صحيح (iframe)"), o("Faux, audio=YouTube", "False, audio=YouTube", "خطأ، audio=يوتيوب"), o("Faux, ul=YouTube", "False, ul=YouTube", "خطأ، ul=يوتيوب"), o("Faux, mark=YouTube", "False, mark=YouTube", "خطأ، mark=يوتيوب")], 0, "YouTube = iframe.", "YouTube = iframe.", "يوتيوب = iframe."),
    Q("muted :", "muted:", "muted:",
      [o("sans son", "no sound", "بلا صوت"), o("plein écran", "fullscreen", "ملء الشاشة"), o("liste", "list", "قائمة"), o("sémantique header", "semantic header", "header دلالي")], 0, "Muet.", "Mute.", "صامت."),
    Q("Plusieurs source dans audio :", "Several source in audio:", "عدة source في audio:",
      [o("oui, comme video", "yes, like video", "نعم مثل video"), o("interdit", "forbidden", "ممنوع"), o("seulement 1 dans tout HTML", "only 1 in all HTML", "واحد فقط في كل HTML"), o("uniquement dans ol", "only in ol", "في ol فقط")], 0, "Même idée chapitre 9.", "Same idea as chapter 9.", "نفس فكرة الفصل 9."),
    Q("audio est :", "audio is:", "audio هو:",
      [o("un conteneur (peut contenir source + texte)", "a container (can hold source + text)", "حاوية (قد تحتوي source + نص)"), o("vide comme br (jamais de contenu)", "empty like br (never content)", "فارغ مثل br (بلا محتوى أبدًا)"), o("un titre h1", "an h1 heading", "عنوان h1"), o("un charset", "a charset", "charset")], 0, "Pas un void element.", "Not a void element.", "ليس عنصرًا فارغًا."),
],
[
    P(("audio mp3 + controls.", "audio mp3 + controls.", "audio mp3 + controls."), "", "<audio src=\"audio/audio.mp3\" controls></audio>", ("src controls", "src controls", "src controls")),
    P(("Ajoute controls.", "Add controls.", "أضف controls."), "<audio src=\"audio/audio.mp3\"></audio>", "<audio src=\"audio/audio.mp3\" controls></audio>", ("controls", "controls", "controls")),
    P(("3 formats source.", "3 format sources.", "3 صيغ source."), "<audio controls></audio>", "<audio controls>\n<source src=\"audio/audio.mp3\" type=\"audio/mpeg\">\n<source src=\"audio/audio.ogg\" type=\"audio/ogg\">\n<source src=\"audio/audio.wav\" type=\"audio/wav\">\n</audio>", ("mpeg ogg wav", "mpeg ogg wav", "mpeg ogg wav")),
    P(("type audio/mpeg.", "type audio/mpeg.", "type audio/mpeg."), "<source src=\"audio/audio.mp3\">", "<source src=\"audio/audio.mp3\" type=\"audio/mpeg\">", ("type", "type", "type")),
    P(("Fallback.", "Fallback.", "احتياطي."), "<audio src=\"audio/audio.mp3\" controls></audio>", "<audio src=\"audio/audio.mp3\" controls>Votre navigateur ne prend pas en charge l'audio.</audio>", ("texte", "text", "نص")),
    P(("loop.", "loop.", "loop."), "<audio src=\"audio/audio.mp3\" controls></audio>", "<audio src=\"audio/audio.mp3\" controls loop></audio>", ("loop", "loop", "loop")),
    P(("Corrige video pour un mp3.", "Fix video used for mp3.", "صحّح video المستخدم لـ mp3."), "<video src=\"audio/audio.mp3\" controls></video>", "<audio src=\"audio/audio.mp3\" controls></audio>", ("audio", "audio", "audio")),
    P(("Corrige le dossier audios/ → audio/.", "Fix folder audios/ → audio/.", "صحّح المجلد audios/ → audio/."), "<source src=\"audios/audio.mp3\" type=\"audio/mpeg\">", "<source src=\"audio/audio.mp3\" type=\"audio/mpeg\">", ("chemin du cours.", "course path.", "مسار الدرس.")),
    P(("h2 message vendeur + audio.", "h2 seller message + audio.", "h2 رسالة البائع + audio."), "", "<h2>Écoutez la description</h2>\n<audio src=\"audio/audio.mp3\" controls></audio>", ("exemple réel.", "real example.", "مثال حقيقي.")),
    P(("preload none.", "preload none.", "preload none."), "<audio src=\"a.mp3\" controls></audio>", "<audio src=\"a.mp3\" controls preload=\"none\"></audio>", ("preload", "preload", "preload")),
    P(("muted.", "muted.", "muted."), "<audio src=\"a.mp3\" controls></audio>", "<audio src=\"a.mp3\" controls muted></audio>", ("muted", "muted", "muted")),
    P(("article + audio.", "article + audio.", "article + audio."), "", "<article>\n<h3>Message du vendeur</h3>\n<audio src=\"audio/audio.mp3\" controls></audio>\n</article>", ("conteneur", "container", "حاوية")),
    P(("Deuxieme source ogg.", "Second ogg source.", "source ogg ثانٍ."), "<audio controls>\n<source src=\"a.mp3\" type=\"audio/mpeg\">\n</audio>", "<audio controls>\n<source src=\"a.mp3\" type=\"audio/mpeg\">\n<source src=\"a.ogg\" type=\"audio/ogg\">\n</audio>", ("ajouter", "add", "أضف")),
    P(("type wav.", "wav type.", "نوع wav."), "<source src=\"a.wav\">", "<source src=\"a.wav\" type=\"audio/wav\">", ("audio/wav", "audio/wav", "audio/wav")),
    P(("Ne pas mettre width height comme une image.", "Do not set width height like an image.", "لا تضع width height كالصورة."), "<audio src=\"a.mp3\" controls width=\"500\" height=\"500\"></audio>", "<audio src=\"a.mp3\" controls></audio>", ("inutile.", "useless.", "غير مفيد.")),
    P(("autoplay muted (si test).", "autoplay muted (if testing).", "autoplay muted (للتجربة)."), "<audio src=\"a.mp3\" controls></audio>", "<audio src=\"a.mp3\" controls autoplay muted></audio>", ("souvent bloqué sinon.", "often blocked otherwise.", "يُحظر غالبًا وإلا.")),
    P(("figure + audio + légende.", "figure + audio + caption.", "figure + audio + تعليق."), "", "<figure>\n<audio src=\"audio/audio.mp3\" controls></audio>\n<figcaption>Description orale de l'annonce</figcaption>\n</figure>", ("figcaption", "figcaption", "figcaption")),
    P(("Corrige type video/mp4 sur mp3.", "Fix video/mp4 type on mp3.", "صحّح type video/mp4 على mp3."), "<source src=\"a.mp3\" type=\"video/mp4\">", "<source src=\"a.mp3\" type=\"audio/mpeg\">", ("audio/mpeg", "audio/mpeg", "audio/mpeg")),
    P(("p + audio.", "p + audio.", "p + audio."), "", "<p>Écoutez avant d'acheter :</p>\n<audio src=\"audio/audio.mp3\" controls></audio>", ("intro", "intro", "مقدمة")),
    P(("Lecteur complet 3 formats.", "Full player 3 formats.", "مشغّل كامل 3 صيغ."), "", "<audio controls>\n<source src=\"audio/audio.mp3\" type=\"audio/mpeg\">\n<source src=\"audio/audio.ogg\" type=\"audio/ogg\">\n<source src=\"audio/audio.wav\" type=\"audio/wav\">\nTon navigateur ne lit pas l'audio HTML5.\n</audio>", ("notes chapitre 10.", "chapter 10 notes.", "ملاحظات الفصل 10.")),
])
print("ch9-10 ok")
