# -*- coding: utf-8 -*-
from gen_exos import T, Q, P, o, make_ch

make_ch("chapitre-7", "chapitre-7.md", T("Chapitre 7 — Les icônes", "Chapter 7 — Icons", "الفصل 7 — الأيقونات"),
[
    Q("Deux familles d’icônes vues en cours :", "Two icon families in this course:", "عائلتا الأيقونات في الدرس:",
      [o("image img / police d’icônes (i + librairie)", "img image / icon font (i + library)", "صورة img / خط أيقونات (i + مكتبة)"), o("video / audio seulement", "video / audio only", "video / audio فقط"), o("ul / ol seulement", "ul / ol only", "ul / ol فقط"), o("iframe / canvas seulement", "iframe / canvas only", "iframe / canvas فقط")], 0, "PNG vs Akar.", "PNG vs Akar.", "PNG مقابل Akar."),
    Q("Icône PNG : on règle la taille avec :", "PNG icon: size is set with:", "أيقونة PNG: الحجم بـ:",
      [o("width et height", "width and height", "width و height"), o("font-size seulement", "font-size only", "font-size فقط"), o("charset", "charset", "charset"), o("controls", "controls", "controls")], 0, "Comme une photo.", "Like a photo.", "مثل صورة."),
    Q("Icône Akar (élément i) : taille avec :", "Akar icon (i element): size with:", "أيقونة Akar (عنصر i): الحجم بـ:",
      [o("font-size", "font-size", "font-size"), o("width/height d’image", "image width/height", "width/height للصورة"), o("start d’ol", "ol start", "start لـ ol"), o("poster", "poster", "poster")], 0, "C’est du texte.", "It is text.", "إنه نص."),
    Q("Couleur d’une icône Akar :", "Color of an Akar icon:", "لون أيقونة Akar:",
      [o("color (comme le texte)", "color (like text)", "color (مثل النص)"), o("alt", "alt", "alt"), o("src", "src", "src"), o("type video/mp4", "type video/mp4", "type video/mp4")], 0, "style=\"color:...\"", "style=\"color:...\"", "style=\"color:...\"."),
    Q("Le script Akar se colle dans :", "The Akar script is pasted in:", "سكربت Akar يُلصق في:",
      [o("head", "head", "head"), o("le fichier MP3", "the MP3 file", "ملف MP3"), o("un li obligatoire", "a required li", "li إلزامي"), o("après </html>", "after </html>", "بعد </html>")], 0, "Bibliothèque JS.", "JS library.", "مكتبة JS."),
    Q("Flaticon sert à :", "Flaticon is used to:", "Flaticon لـ:",
      [o("trouver et télécharger un PNG", "find and download a PNG", "العثور على PNG وتنزيله"), o("héberger YouTube", "host YouTube", "استضافة يوتيوب"), o("créer un dl", "create a dl", "إنشاء dl"), o("remplacer UTF-8", "replace UTF-8", "تعويض UTF-8")], 0, "Puis img src.", "Then img src.", "ثم img src."),
    Q("ai-facebook-fill est :", "ai-facebook-fill is:", "ai-facebook-fill هو:",
      [o("une classe CSS de l’icône", "a CSS class of the icon", "فئة CSS للأيقونة"), o("un charset", "a charset", "charset"), o("un type audio", "an audio type", "نوع صوت"), o("un élément ul", "a ul element", "عنصر ul")], 0, "class=\"ai-...\"", "class=\"ai-...\"", "class=\"ai-...\"."),
    Q("On peut cliquer une icône si :", "An icon is clickable if:", "الأيقونة قابلة للنقر إذا:",
      [o("on l’entoure d’un a", "we wrap it with an a", "لففناها بـ a"), o("on ajoute controls", "we add controls", "أضفنا controls"), o("on met ol", "we put ol", "وضعنا ol"), o("on retire href partout", "we remove href everywhere", "أزلنا href من كل مكان")], 0, "Comme une image-lien.", "Like a linked image.", "مثل صورة-رابط."),
    Q("Sans le script Akar, le i :", "Without the Akar script, i:", "بدون سكربت Akar، i:",
      [o("reste de l’italique / pas l’icône", "stays italic / not the icon", "يبقى مائلًا / ليست الأيقونة"), o("devient une video", "becomes a video", "يصبح فيديو"), o("crée un favicon", "creates a favicon", "ينشئ أيقونة تبويب"), o("est un iframe", "is an iframe", "iframe")], 0, "La librairie transforme i.", "The library transforms i.", "المكتبة تحوّل i."),
    Q("PNG figé vs police :", "Fixed PNG vs font:", "PNG ثابت مقابل الخط:",
      [o("changer la couleur d’un PNG est plus dur ; la police se recolore", "recoloring a PNG is harder; a font recolors", "تغيير لون PNG أصعب؛ الخط يُلوَّن"), o("c’est identique à ol", "it is identical to ol", "مطابق لـ ol"), o("PNG a besoin de controls", "PNG needs controls", "PNG يحتاج controls"), o("la police a besoin de src mp4", "the font needs mp4 src", "الخط يحتاج src mp4")], 0, "Avantage Akar : color.", "Akar benefit: color.", "ميزة Akar: color."),
    Q("Étapes Akar : Get started → script GitHub → snippet HTML.", "Akar steps: Get started → GitHub script → HTML snippet.", "خطوات Akar: Get started → سكربت GitHub → قصاصة HTML.",
      [o("Vrai", "True", "صحيح"), o("Faux, on utilise seulement ol", "False, we only use ol", "خطأ، نستخدم ol فقط"), o("Faux, Akar est une video", "False, Akar is a video", "خطأ، Akar فيديو"), o("Faux, ça va dans dl", "False, it goes in dl", "خطأ، يذهب إلى dl")], 0, "Comme dans tes notes.", "As in your notes.", "كما في ملاحظاتك."),
    Q("img alt sur une icône image :", "img alt on an image icon:", "img alt على أيقونة صورة:",
      [o("toujours utile (accessibilité)", "always useful (accessibility)", "مفيد دائمًا (إتاحة)"), o("interdit", "forbidden", "ممنوع"), o("remplace le script Akar", "replaces the Akar script", "يعوّض سكربت Akar"), o("est un iframe", "is an iframe", "iframe")], 0, "Décrire l’icône.", "Describe the icon.", "صف الأيقونة."),
    Q("font-size: 46px sur i :", "font-size: 46px on i:", "font-size: 46px على i:",
      [o("agrandit l’icône police", "enlarges the font icon", "يكبّر أيقونة الخط"), o("crée 46 listes", "creates 46 lists", "ينشئ 46 قائمة"), o("est un charset", "is a charset", "charset"), o("ouvre YouTube", "opens YouTube", "يفتح يوتيوب")], 0, "Comme une police d’écriture.", "Like a typeface.", "مثل خط كتابة."),
    Q("On copie seulement le script, pas toute la page GitHub.", "We copy only the script, not the whole GitHub page.", "ننسخ السكربت فقط لا صفحة GitHub كلها.",
      [o("Vrai", "True", "صحيح"), o("Faux", "False", "خطأ"), o("On copie un mp3", "We copy an mp3", "ننسخ mp3"), o("On copie un ol", "We copy an ol", "ننسخ ol")], 0, "Une balise script.", "One script tag.", "وسم script واحد."),
    Q("Une icône image n’a pas besoin d’Internet une fois téléchargée.", "An image icon does not need the Internet once downloaded.", "أيقونة الصورة لا تحتاج الإنترنت بعد التنزيل.",
      [o("Vrai (fichier local)", "True (local file)", "صحيح (ملف محلي)"), o("Faux, toujours YouTube", "False, always YouTube", "خطأ، يوتيوب دائمًا"), o("Faux, besoin de Akar", "False, needs Akar", "خطأ، تحتاج Akar"), o("Faux, besoin de ol", "False, needs ol", "خطأ، تحتاج ol")], 0, "PNG dans icones/.", "PNG in icones/.", "PNG في icones/."),
    Q("Akar a besoin d’Internet pour charger le script unpkg.", "Akar needs the Internet to load the unpkg script.", "Akar تحتاج الإنترنت لتحميل سكربت unpkg.",
      [o("Vrai en général", "True in general", "صحيح عمومًا"), o("Faux, c’est un PNG local", "False, it is a local PNG", "خطأ، إنه PNG محلي"), o("Faux, c’est ol", "False, it is ol", "خطأ، إنه ol"), o("Faux, c’est charset", "False, it is charset", "خطأ، إنه charset")], 0, "CDN.", "CDN.", "CDN."),
    Q("i était à l’origine :", "Originally i was:", "i كان أصلًا:",
      [o("italique", "italic", "مائل"), o("iframe", "iframe", "iframe"), o("image", "image", "صورة"), o("input", "input", "input")], 0, "Réutilisé pour les icônes.", "Reused for icons.", "أُعيد استخدامه للأيقونات."),
    Q("Mettre width=46 sur un i Akar :", "Setting width=46 on an Akar i:", "وضع width=46 على i Akar:",
      [o("n’est pas la bonne méthode (utiliser font-size)", "is not the right method (use font-size)", "ليست الطريقة الصحيحة (استخدم font-size)"), o("est obligatoire", "is required", "إلزامي"), o("crée un mp4", "creates an mp4", "ينشئ mp4"), o("remplace head", "replaces head", "يعوّض head")], 0, "Police ≠ bitmap.", "Font ≠ bitmap.", "خط ≠ صورة نقطية."),
    Q("Icône dans le menu :", "Icon in the menu:", "أيقونة في القائمة:",
      [o("a > i ou a > img", "a > i or a > img", "a > i أو a > img"), o("source type audio", "source type audio", "source نوع صوت"), o("seulement hr", "hr only", "hr فقط"), o("seulement meta", "meta only", "meta فقط")], 0, "Lien + icône.", "Link + icon.", "رابط + أيقونة."),
    Q("html-5.png dans icones/ s’affiche avec :", "html-5.png in icones/ is shown with:", "html-5.png في icones/ يُعرض بـ:",
      [o("img src=\"icones/html-5.png\"", "img src=\"icones/html-5.png\"", "img src=\"icones/html-5.png\""), o("audio src", "audio src", "audio src"), o("iframe youtube", "iframe youtube", "iframe يوتيوب"), o("ol type=A", "ol type=A", "ol type=A")], 0, "Méthode 1.", "Method 1.", "الطريقة 1."),
],
[
    P(("img icône 48×48.", "img icon 48×48.", "img أيقونة 48×48."), "", "<img src=\"icones/html.png\" alt=\"HTML\" width=\"48\" height=\"48\">", ("width height", "width height", "width height")),
    P(("Script Akar dans head.", "Akar script in head.", "سكربت Akar في head."), "<head></head>", "<head>\n<script src=\"https://unpkg.com/akar-icons-fonts\"></script>\n</head>", ("script", "script", "script")),
    P(("i facebook bleu 46px.", "i facebook blue 46px.", "i فيسبوك أزرق 46px."), "", "<i class=\"ai-facebook-fill\" style=\"color: blue; font-size: 46px;\"></i>", ("class + style", "class + style", "class + style")),
    P(("Icône dans un lien.", "Icon inside a link.", "أيقونة داخل رابط."), "<i class=\"ai-facebook-fill\"></i>", "<a href=\"https://www.facebook.com\"><i class=\"ai-facebook-fill\"></i></a>", ("a enveloppe.", "a wraps.", "a يلف.")),
    P(("img cliquable W3Schools.", "Clickable img W3Schools.", "img قابل للنقر W3Schools."), "<img src=\"icones/html.png\" alt=\"HTML\">", "<a href=\"https://www.w3schools.com\"><img src=\"icones/html.png\" alt=\"HTML\" width=\"24\" height=\"24\"></a>", ("a + img", "a + img", "a + img")),
    P(("Passe 64px en font-size.", "Switch 64px to font-size.", "حوّل 64px إلى font-size."), "<i class=\"ai-instagram-fill\" style=\"width:64px\"></i>", "<i class=\"ai-instagram-fill\" style=\"font-size:64px; color:#e1306c;\"></i>", ("font-size + color", "font-size + color", "font-size + color")),
    P(("Trois icônes sociales.", "Three social icons.", "ثلاث أيقونات اجتماعية."), "", "<i class=\"ai-facebook-fill\" style=\"color:#1877f2;font-size:40px;\"></i>\n<i class=\"ai-instagram-fill\" style=\"color:#e1306c;font-size:40px;\"></i>\n<i class=\"ai-whatsapp-fill\" style=\"color:#25d366;font-size:40px;\"></i>", ("3 i", "3 i", "3 i")),
    P(("alt sur icône image.", "alt on image icon.", "alt على أيقونة صورة."), "<img src=\"icones/html-5.png\" width=\"64\" height=\"64\">", "<img src=\"icones/html-5.png\" alt=\"HTML 5\" width=\"64\" height=\"64\">", ("alt", "alt", "alt")),
    P(("title sur img icône.", "title on icon img.", "title على img أيقونة."), "<img src=\"icones/html.png\" alt=\"HTML\">", "<img src=\"icones/html.png\" alt=\"HTML\" title=\"Logo HTML\">", ("title", "title", "title")),
    P(("Réduis l’image à 20px.", "Shrink the image to 20px.", "صغّر الصورة إلى 20px."), "<img src=\"icones/html.png\" alt=\"HTML\" width=\"100\" height=\"100\">", "<img src=\"icones/html.png\" alt=\"HTML\" width=\"20\" height=\"20\">", ("20", "20", "20")),
    P(("WhatsApp lien.", "WhatsApp link.", "رابط واتساب."), "", "<a href=\"https://www.whatsapp.com\"><i class=\"ai-whatsapp-fill\" style=\"color:#25d366;font-size:36px;\"></i></a>", ("a+i", "a+i", "a+i")),
    P(("Deux méthodes côte à côte.", "Both methods side by side.", "الطريقتان جنبًا إلى جنب."), "", "<img src=\"icones/html.png\" alt=\"PNG\" width=\"40\" height=\"40\">\n<i class=\"ai-facebook-fill\" style=\"font-size:40px;color:blue;\"></i>", ("img + i", "img + i", "img + i")),
    P(("style color purple.", "style color purple.", "style color purple."), "<i class=\"ai-facebook-fill\"></i>", "<i class=\"ai-facebook-fill\" style=\"color:purple; font-size:32px;\"></i>", ("color", "color", "color")),
    P(("Icônes dans ul.", "Icons in ul.", "أيقونات داخل ul."), "", "<ul>\n<li><i class=\"ai-facebook-fill\"></i> Facebook</li>\n<li><i class=\"ai-instagram-fill\"></i> Instagram</li>\n</ul>", ("li + i", "li + i", "li + i")),
    P(("Corrige width sur i.", "Fix width on i.", "صحّح width على i."), "<i class=\"ai-facebook-fill\" width=\"46\"></i>", "<i class=\"ai-facebook-fill\" style=\"font-size:46px;\"></i>", ("font-size", "font-size", "font-size")),
    P(("Chemin icones/html-5.png.", "Path icones/html-5.png.", "مسار icones/html-5.png."), "<img alt=\"HTML5\">", "<img src=\"icones/html-5.png\" alt=\"HTML5\" width=\"48\" height=\"48\">", ("src", "src", "src")),
    P(("script + i ensemble.", "script + i together.", "script + i معًا."), "<html><head></head><body></body></html>", "<html><head>\n<script src=\"https://unpkg.com/akar-icons-fonts\"></script>\n</head>\n<body>\n<i class=\"ai-facebook-fill\" style=\"font-size:40px;color:blue;\"></i>\n</body></html>", ("head script, body i.", "head script, body i.", "head script و body i.")),
    P(("Accessibilité : alt descriptif.", "A11y: descriptive alt.", "إتاحة: alt وصفي."), "<img src=\"icones/html.png\">", "<img src=\"icones/html.png\" alt=\"Logo du langage HTML\">", ("alt clair.", "clear alt.", "alt واضح.")),
    P(("Instagram 28px rose.", "Instagram 28px pink.", "إنستغرام 28px وردي."), "", "<i class=\"ai-instagram-fill\" style=\"color:#e1306c; font-size:28px;\"></i>", ("font-size 28", "font-size 28", "font-size 28")),
    P(("Rangée vendeur : 2 liens icônes.", "Seller row: 2 icon links.", "صف البائع: رابطا أيقونات."), "", "<p>\n<a href=\"https://www.facebook.com\"><i class=\"ai-facebook-fill\" style=\"color:#1877f2;font-size:28px;\"></i></a>\n<a href=\"https://www.instagram.com\"><i class=\"ai-instagram-fill\" style=\"color:#e1306c;font-size:28px;\"></i></a>\n</p>", ("exemple réel du cours.", "real course example.", "مثال الدرس الحقيقي.")),
])

make_ch("chapitre-8", "chapitre-8.md", T("Chapitre 8 — Conteneurs sémantiques et non sémantiques", "Chapter 8 — Semantic and non-semantic containers", "الفصل 8 — الحاويات الدلالية وغير الدلالية"),
[
    Q("Un conteneur :", "A container:", "الحاوية:",
      [o("regroupe d’autres éléments dans un cadre", "groups other elements in a frame", "تجمع عناصر أخرى في إطار"), o("est forcément une video", "is necessarily a video", "فيديو حتمًا"), o("remplace UTF-8", "replaces UTF-8", "تعوّض UTF-8"), o("est un fichier MP3", "is an MP3 file", "ملف MP3")], 0, "Carte Ouedkniss = une boîte.", "Ouedkniss card = one box.", "بطاقة الإعلان = صندوق واحد."),
    Q("Non sémantique veut dire :", "Non-semantic means:", "غير دلالي يعني:",
      [o("le nom ne dit pas le métier (div, span)", "the name does not state the job (div, span)", "الاسم لا يوضح المهمة (div و span)"), o("interdit en HTML", "forbidden in HTML", "ممنوع في HTML"), o("uniquement YouTube", "YouTube only", "يوتيوب فقط"), o("uniquement ol", "ol only", "ol فقط")], 0, "Générique.", "Generic.", "عام."),
    Q("Sémantique veut dire :", "Semantic means:", "دلالي يعني:",
      [o("le nom donne le job (header, article…)", "the name gives the job (header, article…)", "الاسم يعطي المهمة (header و article…)"), o("plus de CSS possible", "no CSS possible", "لا يمكن CSS"), o("élément vide", "empty element", "عنصر فارغ"), o("commentaire", "comment", "تعليق")], 0, "HTML5.", "HTML5.", "HTML5."),
    Q("div est :", "div is:", "div هو:",
      [o("bloc générique", "generic block", "كتلة عامة"), o("un titre h1", "an h1 heading", "عنوان h1"), o("un type audio", "an audio type", "نوع صوت"), o("un iframe YouTube", "a YouTube iframe", "iframe يوتيوب")], 0, "Non sémantique.", "Non-semantic.", "غير دلالي."),
    Q("span est :", "span is:", "span هو:",
      [o("en ligne, générique", "inline, generic", "ضمن السطر وعام"), o("un footer", "a footer", "footer"), o("un ol", "an ol", "ol"), o("un source", "a source", "source")], 0, "Dans la phrase.", "In the sentence.", "داخل الجملة."),
    Q("header :", "header:", "header:",
      [o("en-tête (logo, titre, parfois menu)", "page/section header (logo, title, sometimes menu)", "ترويسة (شعار، عنوان، أحيانًا قائمة)"), o("pied de page", "page footer", "تذييل"), o("une video", "a video", "فيديو"), o("un charset", "a charset", "charset")], 0, "Haut de page.", "Top of page.", "أعلى الصفحة."),
    Q("nav :", "nav:", "nav:",
      [o("navigation / menu", "navigation / menu", "تنقل / قائمة"), o("audio", "audio", "صوت"), o("emoji", "emoji", "إيموجي"), o("favicon seulement", "favicon only", "أيقونة تبويب فقط")], 0, "Liens de menu.", "Menu links.", "روابط القائمة."),
    Q("main :", "main:", "main:",
      [o("contenu principal, un seul par page", "main content, one per page", "المحتوى الرئيسي، واحد في الصفحة"), o("autant que de div", "as many as divs", "بعدد div"), o("dans head", "in head", "في head"), o("un élément vide", "an empty element", "عنصر فارغ")], 0, "Un main.", "One main.", "main واحد."),
    Q("article :", "article:", "article:",
      [o("contenu indépendant (une annonce)", "independent content (a listing)", "محتوى مستقل (إعلان)"), o("uniquement un journal papier", "a paper newspaper only", "جريدة ورقية فقط"), o("un br", "a br", "br"), o("un mp3", "an mp3", "mp3")], 0, "Carte d’annonce.", "Listing card.", "بطاقة إعلان."),
    Q("section :", "section:", "section:",
      [o("partie thématique", "thematic part", "جزء موضوعي"), o("un saut de ligne", "a line break", "سطر جديد"), o("un type video", "a video type", "نوع فيديو"), o("un commentaire", "a comment", "تعليق")], 0, "Ex. « Téléphones ».", "E.g. “Phones”.", "مثال «هواتف»."),
    Q("aside :", "aside:", "aside:",
      [o("contenu à côté (pub, secondaire)", "side content (ad, secondary)", "محتوى جانبي (إعلان، ثانوي)"), o("le h1 obligatoire", "the required h1", "h1 الإلزامي"), o("un ol type A", "an ol type A", "ol type A"), o("meta charset", "meta charset", "meta charset")], 0, "Barre latérale.", "Sidebar.", "شريط جانبي."),
    Q("footer :", "footer:", "footer:",
      [o("pied de page", "page footer", "تذييل الصفحة"), o("en-tête", "header bar", "ترويسة"), o("un source", "a source", "source"), o("un mark", "a mark", "mark")], 0, "Copyright, contact.", "Copyright, contact.", "حقوق، اتصال."),
    Q("Pourquoi pas que des div ?", "Why not only divs?", "لماذا لا نستخدم div فقط؟",
      [o("SEO / accessibilité / clarté : le moteur aime le sens", "SEO / a11y / clarity: the engine likes meaning", "SEO / إتاحة / وضوح: المحرك يحب المعنى"), o("div est interdit", "div is forbidden", "div ممنوع"), o("div casse UTF-8", "div breaks UTF-8", "div يكسر UTF-8"), o("div ne peut pas contenir img", "div cannot contain img", "div لا يحتوي img")], 0, "Mixte sémantique + div.", "Mix semantics + div.", "مزيج دلالي + div."),
    Q("La carte Ouedkniss est plutôt un :", "The Ouedkniss card is rather an:", "بطاقة الإعلان هي بالأحرى:",
      [o("article (ou div si juste le CSS)", "article (or div if only CSS)", "article (أو div إن كان CSS فقط)"), o("title d’onglet", "tab title", "عنوان تبويب"), o("source mp3", "mp3 source", "source mp3"), o("DOCTYPE", "DOCTYPE", "DOCTYPE")], 0, "Contenu indépendant.", "Independent content.", "محتوى مستقل."),
    Q("figure + figcaption :", "figure + figcaption:", "figure + figcaption:",
      [o("image + légende", "image + caption", "صورة + تعليق"), o("audio + video", "audio + video", "صوت + فيديو"), o("head + body", "head + body", "head + body"), o("ul + ol", "ul + ol", "ul + ol")], 0, "Légende liée à l’image.", "Caption tied to the image.", "تعليق مرتبط بالصورة."),
    Q("details / summary :", "details / summary:", "details / summary:",
      [o("bloc repliable « voir plus »", "collapsible “see more” block", "كتلة قابلة للطي «عرض المزيد»"), o("un iframe YouTube", "a YouTube iframe", "iframe يوتيوب"), o("un charset", "a charset", "charset"), o("un favicon", "a favicon", "أيقونة تبويب")], 0, "Interactif natif.", "Native interactive.", "تفاعلي أصلي."),
    Q("html / head / body sont :", "html / head / body are:", "html / head / body هي:",
      [o("conteneurs racine (page / config / visible)", "root containers (page / config / visible)", "حاويات جذر (صفحة / إعداد / ظاهر)"), o("des listes", "lists", "قوائم"), o("des videos", "videos", "فيديوهات"), o("des emojis", "emojis", "إيموجي")], 0, "Structure globale.", "Global structure.", "هيكل عام."),
    Q("span vs div :", "span vs div:", "span مقابل div:",
      [o("span en ligne, div bloc", "span inline, div block", "span ضمن السطر، div كتلة"), o("identiques", "identical", "متطابقان"), o("span va dans head", "span goes in head", "span في head"), o("div est vide comme br", "div is empty like br", "div فارغ مثل br")], 0, "Choix selon le flux.", "Choose by flow.", "الاختيار حسب التدفق."),
    Q("On mélange sémantique et div quand :", "We mix semantics and div when:", "نمزج الدلالة و div عندما:",
      [o("la zone a un nom (sémantique) ou c’est juste du CSS (div)", "the area has a name (semantic) or it is just CSS (div)", "للمنطقة اسم (دلالي) أو مجرد CSS (div)"), o("jamais", "never", "أبدًا"), o("seulement sans charset", "only without charset", "بدون charset فقط"), o("seulement dans ol", "only in ol", "في ol فقط")], 0, "Règle du chapitre 8.", "Chapter 8 rule.", "قاعدة الفصل 8."),
    Q("Plusieurs articles vont dans :", "Several articles go in:", "عدة article توضع في:",
      [o("souvent une section", "often a section", "غالبًا section"), o("un unique h1 chacun dans head", "each unique h1 in head", "كل h1 في head"), o("un source", "a source", "source"), o("un target _blank", "a target _blank", "target _blank")], 0, "Section « Téléphones ».", "“Phones” section.", "قسم «هواتف»."),
],
[
    P(("header avec h1.", "header with h1.", "header مع h1."), "", "<header><h1>Ouedkniss</h1></header>", ("header", "header", "header")),
    P(("nav de 2 liens.", "nav of 2 links.", "nav من رابطين."), "", "<nav><a href=\"#\">Accueil</a> <a href=\"#\">Annonces</a></nav>", ("nav", "nav", "nav")),
    P(("footer copyright.", "footer copyright.", "footer حقوق."), "", "<footer><p>© 2026 Mini Ouedkniss</p></footer>", ("footer", "footer", "footer")),
    P(("article annonce.", "listing article.", "article إعلان."), "", "<article>\n<h3>iPhone 13</h3>\n<p>Alger — 85000 DA</p>\n</article>", ("article", "article", "article")),
    P(("section + 2 articles.", "section + 2 articles.", "section + articleان."), "", "<section>\n<h2>Téléphones</h2>\n<article><h3>iPhone</h3></article>\n<article><h3>Galaxy</h3></article>\n</section>", ("section enveloppe.", "section wraps.", "section يلف.")),
    P(("aside pub.", "aside ad.", "aside إعلان."), "", "<aside><p>Publicité</p></aside>", ("aside", "aside", "aside")),
    P(("main autour du contenu.", "main around content.", "main حول المحتوى."), "<h2>Annonces</h2>", "<main>\n<h2>Annonces</h2>\n</main>", ("un main.", "one main.", "main واحد.")),
    P(("div carte générique.", "generic div card.", "بطاقة div عامة."), "", "<div>\n<img src=\"v.png\" alt=\"voiture\">\n<h2>Peugeot 208</h2>\n<p>Prix : <span>1850000 DA</span></p>\n</div>", ("div + span", "div + span", "div + span")),
    P(("Remplace div menu par nav.", "Replace menu div with nav.", "استبدل div القائمة بـ nav."), "<div><a href=\"#\">Accueil</a></div>", "<nav><a href=\"#\">Accueil</a></nav>", ("sémantique.", "semantics.", "دلالي.")),
    P(("Remplace div pied par footer.", "Replace bottom div with footer.", "استبدل div الأسفل بـ footer."), "<div>© 2026</div>", "<footer>© 2026</footer>", ("footer", "footer", "footer")),
    P(("figure légende.", "figure caption.", "figure تعليق."), "", "<figure>\n<img src=\"v.png\" alt=\"208\">\n<figcaption>Peugeot 208 — Alger</figcaption>\n</figure>", ("figcaption dans figure.", "figcaption in figure.", "figcaption داخل figure.")),
    P(("details voir plus.", "details see more.", "details عرض المزيد."), "", "<details>\n<summary>Voir plus</summary>\n<p>Première main.</p>\n</details>", ("summary", "summary", "summary")),
    P(("span sur le prix.", "span on the price.", "span على السعر."), "<p>Prix : 85000 DA</p>", "<p>Prix : <span>85000 DA</span></p>", ("span", "span", "span")),
    P(("header + nav ensemble.", "header + nav together.", "header + nav معًا."), "", "<header>\n<h1>Ouedkniss</h1>\n<nav><a href=\"#\">Annonces</a></nav>\n</header>", ("nav dans header OK.", "nav in header is OK.", "nav داخل header جائز.")),
    P(("Page squelette sémantique.", "Semantic skeleton page.", "هيكل صفحة دلالي."), "<body></body>", "<body>\n<header><h1>Site</h1></header>\n<main><article><h2>Annonce</h2></article></main>\n<footer>© 2026</footer>\n</body>", ("3 zones.", "3 zones.", "3 مناطق.")),
    P(("aside à côté de section (ordre HTML).", "aside next to section (HTML order).", "aside بجانب section (ترتيب HTML)."), "", "<main>\n<section><h2>Annonces</h2></section>\n<aside>Pub</aside>\n</main>", ("main contient les deux.", "main contains both.", "main يحتويهما.")),
    P(("Ne pas mettre 2 main.", "Do not put 2 main.", "لا تضع mainين."), "<main>A</main>\n<main>B</main>", "<main>\n<section>A</section>\n<section>B</section>\n</main>", ("un main, plusieurs section.", "one main, several section.", "main واحد وعدة section.")),
    P(("Carte : article pas div (sémantique).", "Card: article not div (semantic).", "بطاقة: article لا div (دلالي)."), "<div><h3>iPhone 13</h3><p>Alger</p></div>", "<article><h3>iPhone 13</h3><p>Alger</p></article>", ("article", "article", "article")),
    P(("address contact.", "address contact.", "address اتصال."), "", "<address>Karim — Hydra — 0550</address>", ("address", "address", "address")),
    P(("Mini Ouedkniss complet.", "Full mini Ouedkniss.", "Ouedkniss مصغر كامل."), "", "<header><h1>Ouedkniss</h1><nav><a href=\"#\">Accueil</a></nav></header>\n<main>\n<section>\n<article><h3>iPhone 13</h3><p>Alger</p></article>\n</section>\n<aside>Publicité</aside>\n</main>\n<footer>© 2026</footer>", ("toutes les zones.", "all zones.", "كل المناطق.")),
])
print("ch7-8 ok")
